#!/usr/bin/env python3
"""Generate `internal/store/testdata/citation_ids.json` — the citation-id ORACLE.

🔴 WHY A GENERATED FIXTURE RATHER THAN TWO TEST SUITES. `JournalBullet.citation_id`
exists in BOTH languages (`lib/subsystem_resolver.py` and `internal/store`), because
`packages.cairn` installs the Python client and its `lib/` under `libexec` and nothing
else — so `lib/` CANNOT import `internal/`. That is packaging, not a choice anyone may
undo here, and it is the same shape `AGENTS.md` already blesses for
`server/Dockerfile` against `flake.nix`'s `serverEnv`.

Two independent implementations of a hash must agree FOREVER, or the id stops being a
shared name for a bullet and silently becomes two. This file writes the PYTHON answers
down; `internal/store`'s test replays the same bodies and asserts the same strings. So:

  * a change to either implementation turns the Go test red;
  * a REGENERATION that moves an id shows up as a diff in review, not as a green run.

⚠ IT PINS THE ID, NOT THE PARSE. The fixture also carries each bullet's `start_line`
and `lines`, so a parser change that re-groups bullets is caught too — but the bodies
below are hand-written, so this says nothing about the LIVE corpus. The differential
reader fixture (`tests/reader_fixtures.py`) is what compares rendered bytes over a
synthetic world, and `tests/parity/harness.py` is what compares the two real clients.

🔴 REGENERATE AND DIFF, NEVER HAND-EDIT — the same rule
`internal/report/testdata/reader_fixtures.json` carries. A hand-edited oracle agrees
with nothing.

    python3 tests/citation_ids.py > internal/store/testdata/citation_ids.json
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "lib"))

from subsystem_resolver import parse_journal_bullets  # noqa: E402

#: Each case is (name, body). Chosen so every rule the parser states is exercised,
#: because an id is only as stable as the grouping it is computed over.
CASES: tuple[tuple[str, str], ...] = (
    (
        "one-single-line-bullet",
        "- 2026-01-01: a lesson.\n",
    ),
    (
        "wrapped-bullet-is-ONE-bullet",
        # The median live bullet is 3 lines. A per-line id would differ here, which
        # is exactly the mistake this case exists to catch.
        "- 2026-01-01: a lesson that wraps\n  onto a second line\n  and a third.\n",
    ),
    (
        "two-bullets-with-IDENTICAL-opening-lines",
        # 🔴 THE CASE A MAP KEYED ON THE OPENING LINE GETS WRONG. Both bullets open
        # identically and differ only in their continuation, so they must receive
        # DIFFERENT ids and ASCENDING start_lines.
        "- same opening\n  tail A\n- same opening\n  tail B\n",
    ),
    (
        "text-before-the-first-bullet-is-DROPPED",
        # The documented `dropped-lines` shape: the preamble belongs to no bullet, so
        # start_line of the first bullet is NOT 0.
        "preamble prose nobody can address\n- 2026-01-01: the only bullet.\n",
    ),
    (
        "a-dash-line-INSIDE-A-FENCE-is-not-a-bullet",
        # 🔴 THE REASON `start_line` IS EXPOSED AT ALL. A renderer re-detecting bullets
        # would stamp the fenced line; the parser does not, and this pins that.
        "- real bullet\n  ```\n  - not a bullet\n  ```\n- second real bullet\n",
    ),
    (
        "trailing-blank-lines-are-stripped-from-lines",
        # So `len(lines)` is NOT the distance to the next start_line — the property the
        # field's docstring warns about.
        "- first\n\n\n- second\n",
    ),
    (
        "markers-do-not-change-the-id-derivation",
        # The id is over the bytes, so an OPEN and a RESOLVED bullet are just different
        # bytes. Included so a future "hash the semantic fields instead" refactor fails.
        "- 2026-01-01: OPEN: unfinished.\n- 2026-01-02: RESOLVED abc1234: done.\n",
    ),
    (
        "unicode-and-emoji-survive-the-utf8-encode",
        # Both sides must hash UTF-8 BYTES. A latin-1 or UTF-16 encode on either side
        # diverges only on non-ASCII, which ASCII-only cases cannot see.
        "- 🔴 a lesson with émoji and accents — and an en dash.\n",
    ),
    (
        "empty-body-yields-no-bullets",
        "",
    ),
)


def main() -> int:
    cases = []
    for name, body in CASES:
        bullets = parse_journal_bullets(body)
        cases.append({
            "name": name,
            "body": body,
            "bullets": [
                {
                    "start_line": b.start_line,
                    "lines": list(b.lines),
                    "citation_id": b.citation_id,
                }
                for b in bullets
            ],
        })
    doc = {
        "_comment": (
            "GENERATED by tests/citation_ids.py from the PYTHON implementation, and "
            "replayed by internal/store's test. Regenerate and diff; never hand-edit."
        ),
        "cases": cases,
    }
    json.dump(doc, sys.stdout, ensure_ascii=False, indent=2, sort_keys=False)
    sys.stdout.write("\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
