package report

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/ZacxDev/cairn/internal/store"
)

// 🔴 THIS IS THE DIFFERENTIAL GATE, AND IT IS WHAT MAKES A GREEN HTTP CORPUS WORTH
// ANYTHING FOR THE RENDERER. The corpus pins the bytes it was told to send, and no row in
// it carries an openness marker, a near-miss marker, a `tasks:` key, a duplicate heading, a
// fenced region, a scope over the 100-line index page, an ambiguous ref, a bare entry, an
// entry with no `## What it is`, an honoured `sensitivity:`, a name-only search hit, a
// sub-threshold near miss, a fuzzy match, a prefix or substring match, a joined compound
// term, a `--max-hits` truncation, a malformed entry BESIDE readable ones, or a
// `search-unreadable` scope. Every one is a branch here.
//
// So the expectations are the ORACLE's own rendered bytes, generated by
// `tests/reader_fixtures.py` and replayed against this port. A hand-written expectation
// would assert what somebody believed the oracle does; these assert what it did.
//
// 🔴 THE TWO THINGS THAT CANNOT BE COMPARED LITERALLY ARE PINNED RATHER THAN IGNORED. The
// store path differs per run, so both sides substitute a placeholder for it; the host
// identity is the ONE line of this output that is SUPPOSED to be machine-dependent, so both
// sides are handed the same synthetic literal. Nothing else is normalized — no header set,
// no "ignore whitespace", no per-case exemptions.
//
// ⚠ AND THE FIXTURE CANNOT GO STALE UNNOTICED: `tests/test_reader_fixtures.py` regenerates
// it and diffs against what is committed, so a reader change that moves the oracle's bytes
// fails there rather than leaving this test comparing against a snapshot of an older
// implementation.

type fixtureFile struct {
	Host             string         `json:"host"`
	StorePlaceholder string         `json:"store_placeholder"`
	Scopes           []string       `json:"scopes"`
	Entries          []fixtureEntry `json:"entries"`
	Cases            []fixtureCase  `json:"cases"`

	DifflibPairs []struct {
		A        string `json:"a"`
		B        string `json:"b"`
		RatioHex string `json:"ratio_hex"`
	} `json:"difflib_pairs"`

	PyRoundCases []struct {
		ValueHex   string `json:"value_hex"`
		Digits     int    `json:"digits"`
		RoundedHex string `json:"rounded_hex"`
	} `json:"py_round_cases"`
}

type fixtureEntry struct {
	Path      string   `json:"path"`
	MTimeNS   int64    `json:"mtime_ns"`
	TextLines []string `json:"text_lines"`
	// StMTimeHex is `os.stat(path).st_mtime.hex()` — the EXACT double CPython computed for
	// this file, so the port's mtime expression is a measurement rather than a comment.
	StMTimeHex string `json:"st_mtime_hex"`
}

type fixtureCase struct {
	ID   string `json:"id"`
	Why  string `json:"why"`
	Kind string `json:"kind"`

	Scope string  `json:"scope"`
	Ref   *string `json:"ref"`
	Limit int     `json:"limit"`
	Mode  string  `json:"mode"`
	Page  int     `json:"page"`

	Query     string  `json:"query"`
	Context   int     `json:"context"`
	Threshold float64 `json:"threshold"`
	MaxHits   int     `json:"max_hits"`
	AllScopes bool    `json:"all_scopes"`

	// Visible is nil for UNRESTRICTED and a (possibly empty) list otherwise — the same
	// asymmetry `store.ScopeSet` carries, and the one a JSON round trip would lose if the
	// field were a plain slice with no pointer: `null` and `[]` are opposites here.
	Visible *[]string `json:"visible"`

	Expect fixtureExpect `json:"expect"`
}

type fixtureExpect struct {
	Status    string   `json:"status"`
	Exit      int      `json:"exit"`
	Warning   string   `json:"warning"`
	TextLines []string `json:"text_lines"`
}

func loadFixture(t *testing.T) fixtureFile {
	t.Helper()
	data, err := os.ReadFile(filepath.Join("testdata", "reader_fixtures.json"))
	if err != nil {
		t.Fatalf("the fixture is the whole test: %v", err)
	}
	var fx fixtureFile
	if err := json.Unmarshal(data, &fx); err != nil {
		t.Fatal(err)
	}
	if len(fx.Cases) == 0 || len(fx.Entries) == 0 {
		// 🔴 THE POSITIVE CONTROL ON THE HARNESS ITSELF. An empty fixture would make every
		// loop below run zero times and report a green with nothing measured, which is the
		// exact failure mode this file exists to close elsewhere.
		t.Fatalf("the fixture declares %d cases over %d entries; a zero here would make "+
			"this whole file vacuous", len(fx.Cases), len(fx.Entries))
	}
	return fx
}

// buildFixtureStore materialises the declared world. MTIMES ARE SET LAST AND FROM THE
// DECLARED INTEGER.
//
// 🔴 NANOSECONDS, NOT A FLOAT, AND BOTH SIDES SET THE SAME INTEGER. A float would be
// converted to nanoseconds twice — once by CPython's `os.utime` and once here — and the
// index order is decided by comparing those numbers, so a one-nanosecond disagreement
// would move a row for reasons that have nothing to do with the renderer. Two entries in
// this world share a whole second and differ only in the fraction, which is precisely
// where that would bite.
func buildFixtureStore(t *testing.T, fx fixtureFile) string {
	t.Helper()
	root := t.TempDir()
	for _, scope := range fx.Scopes {
		if err := os.MkdirAll(filepath.Join(root, scope), 0o755); err != nil {
			t.Fatal(err)
		}
	}
	for _, entry := range fx.Entries {
		target := filepath.Join(root, entry.Path)
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(target, []byte(strings.Join(entry.TextLines, "\n")), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	for _, entry := range fx.Entries {
		target := filepath.Join(root, entry.Path)
		stamp := time.Unix(0, entry.MTimeNS)
		if err := os.Chtimes(target, stamp, stamp); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func (c fixtureCase) visibleSet() store.ScopeSet {
	if c.Visible == nil {
		return store.Unrestricted()
	}
	return store.VisibleScopeSet(*c.Visible)
}

func TestTheRenderedBytesMatchTheORACLEOverShapesTheCorpusCannotSend(t *testing.T) {
	fx := loadFixture(t)
	root := buildFixtureStore(t, fx)
	renderer := Reader{Host: func() string { return fx.Host }}

	for _, tc := range fx.Cases {
		t.Run(tc.ID, func(t *testing.T) {
			var got Rendered
			var err error
			switch tc.Kind {
			case "recall":
				opts := RecallOptions{
					Scope: tc.Scope,
					Limit: tc.Limit,
					Mode:  tc.Mode,
					Page:  tc.Page,
				}
				if tc.Ref != nil {
					opts.Ref, opts.HasRef = *tc.Ref, true
				}
				// The validation ladder is the HANDLER's, not the renderer's, so it is run
				// here too — a fixture row that could not reach the renderer through a real
				// route would be a row measuring something unreachable.
				if vErr := ValidateRecall(opts); vErr != nil {
					t.Fatalf("the fixture row does not pass the option ladder: %v", vErr)
				}
				got, err = renderer.Recall(root, opts, tc.visibleSet())
			case "search":
				opts := SearchOptions{
					Scope:     tc.Scope,
					Query:     tc.Query,
					Context:   tc.Context,
					Threshold: tc.Threshold,
					MaxHits:   tc.MaxHits,
					AllScopes: tc.AllScopes,
				}
				if vErr := ValidateSearch(opts); vErr != nil {
					t.Fatalf("the fixture row does not pass the option ladder: %v", vErr)
				}
				got, err = renderer.Search(root, opts, tc.visibleSet())
			default:
				t.Fatalf("unknown fixture kind %q", tc.Kind)
			}
			if err != nil {
				t.Fatalf("%s (%s): %v", tc.ID, tc.Why, err)
			}
			if got.Status != tc.Expect.Status {
				t.Errorf("status: got %q, want %q", got.Status, tc.Expect.Status)
			}
			if got.Exit != tc.Expect.Exit {
				t.Errorf("exit: got %d, want %d", got.Exit, tc.Expect.Exit)
			}
			// 🔴 THE WARNING IS COMPARED, AND IT IS THE HALF THE ORACLE PRINTS TO STDERR.
			// Porting it as a returned value rather than a write is the one deliberate
			// difference in that path, so the SENTENCE has to be pinned or the difference
			// becomes a silent loss.
			if got.Warning != tc.Expect.Warning {
				t.Errorf("warning:\n got %q\nwant %q", got.Warning, tc.Expect.Warning)
			}
			want := strings.Join(tc.Expect.TextLines, "\n")
			have := strings.ReplaceAll(got.Text, root, fx.StorePlaceholder)
			if have != want {
				t.Errorf("rendered text differs (%s)\n%s", tc.Why, lineDiff(want, have))
			}
		})
	}
}

// lineDiff reports the FIRST differing line and its neighbourhood rather than two walls of
// text. A report body runs to hundreds of lines and a whole-string dump makes the one line
// that moved unfindable, which is how a real divergence gets waved through.
func lineDiff(want, have string) string {
	wantLines := strings.Split(want, "\n")
	haveLines := strings.Split(have, "\n")
	var b strings.Builder
	for i := 0; i < max(len(wantLines), len(haveLines)); i++ {
		w, h := "<absent>", "<absent>"
		if i < len(wantLines) {
			w = wantLines[i]
		}
		if i < len(haveLines) {
			h = haveLines[i]
		}
		if w == h {
			continue
		}
		b.WriteString("  first difference at line ")
		b.WriteString(itoa(i + 1))
		b.WriteString(" of ")
		b.WriteString(itoa(len(wantLines)))
		b.WriteString("\n  oracle: ")
		b.WriteString(w)
		b.WriteString("\n  port:   ")
		b.WriteString(h)
		b.WriteString("\n")
		if len(wantLines) != len(haveLines) {
			b.WriteString("  (and the line COUNT differs: oracle " + itoa(len(wantLines)) +
				", port " + itoa(len(haveLines)) + ")\n")
		}
		return b.String()
	}
	return "  the lines are equal but the strings are not, which means a trailing-newline " +
		"difference\n"
}

func itoa(n int) string {
	if n == 0 {
		return "0"
	}
	var digits []byte
	for n > 0 {
		digits = append([]byte{byte('0' + n%10)}, digits...)
		n /= 10
	}
	return string(digits)
}

func TestTheMTimeIsCPythonsSTMTIMEBitForBit(t *testing.T) {
	// 🔴 THIS CLAIM WAS A COMMENT AND NOTHING ELSE. `pyMtime` is
	// `float64(sec) + 1e-9*float64(nsec)` because that is CPython's own expression, and
	// `float64(nsec)/1e9` is NOT the same double for every nsec — `1e-9` is not exactly
	// representable. A mutant swapping the two SURVIVED the whole rendered-bytes battery,
	// because it takes a pair of timestamps whose relative ORDER flips before any output
	// moves, and this fixture's timestamps are far apart. So the exact double is recorded
	// per entry and compared here.
	//
	// ⚠ EXACT EQUALITY, NOT A TOLERANCE. A tolerance is the assertion that cannot see the
	// defect: the difference IS one bit, and one bit is what flips a comparison.
	fx := loadFixture(t)
	root := buildFixtureStore(t, fx)
	checked, moved := 0, 0
	for _, entry := range fx.Entries {
		if entry.StMTimeHex == "" {
			t.Fatalf("%s declares no st_mtime_hex, so this test is vacuous for it", entry.Path)
		}
		want, err := strconv.ParseFloat(entry.StMTimeHex, 64)
		if err != nil {
			t.Fatalf("%s: %v", entry.Path, err)
		}
		info, err := os.Stat(filepath.Join(root, entry.Path))
		if err != nil {
			t.Fatal(err)
		}
		got := pyMtime(info)
		if got != want {
			t.Errorf("%s: mtime %s, want %s (CPython's st_mtime for the same file)",
				entry.Path, strconv.FormatFloat(got, 'x', -1, 64), entry.StMTimeHex)
		}
		checked++
		// The POSITIVE CONTROL on the fixture's own inputs: a world whose every nsec were
		// 0 would make the two expressions agree trivially and this test would pass with
		// nothing to measure. Count the entries whose fraction is non-zero.
		if entry.MTimeNS%1_000_000_000 != 0 {
			moved++
		}
	}
	if checked == 0 || moved == 0 {
		t.Fatalf("checked %d entries of which %d carry a sub-second fraction; a zero in "+
			"either column makes this test vacuous", checked, moved)
	}
}

func TestTheDIFFLIBRatioIsCPythonsBitForBit(t *testing.T) {
	// 🔴 THE RENDERED BATTERY REACHES THIS FUNCTION ONCE, AT ONE SCORE, AND A MUTATION
	// MEASURED THAT. Relaxing the longest-match tie-break from `k > bestsize` to
	// `k >= bestsize` SURVIVED every rendered case — the decomposition changed and the
	// TOTAL matched size did not, for those two short tokens. So the function is compared
	// directly against CPython over pairs chosen for the mechanisms: typo classes,
	// repeated-character runs where the tie-break really decides the split, a pair whose
	// greedy score is strictly below the LCS, and strings at and over the 200-character
	// boundary where AUTOJUNK engages.
	//
	// ⚠ EXACT EQUALITY. The ratio is PRINTED with two decimals and also SORTED on, so a
	// tolerance would hide precisely the differences that move a line.
	fx := loadFixture(t)
	if len(fx.DifflibPairs) == 0 {
		t.Fatal("no difflib pairs declared, so this test is vacuous")
	}
	sawAutojunk, sawNonTrivial := false, false
	for _, pair := range fx.DifflibPairs {
		want, err := strconv.ParseFloat(pair.RatioHex, 64)
		if err != nil {
			t.Fatalf("%q/%q: %v", pair.A, pair.B, err)
		}
		got := ratio([]rune(pair.A), []rune(pair.B))
		if got != want {
			t.Errorf("ratio(%.20q, %.20q) = %s, CPython says %s",
				pair.A, pair.B, strconv.FormatFloat(got, 'x', -1, 64), pair.RatioHex)
		}
		if len([]rune(pair.B)) >= 200 {
			sawAutojunk = true
		}
		if got != 0.0 && got != 1.0 {
			sawNonTrivial = true
		}
	}
	// The POSITIVE CONTROLS on the table itself: a table of only 0.0 and 1.0 answers would
	// pass against almost any implementation, and one with no long string would leave
	// autojunk — a branch that CHANGES the answer — unreached.
	if !sawAutojunk || !sawNonTrivial {
		t.Fatalf("the table must reach autojunk (>=200 runes on the b side: %v) and produce "+
			"at least one ratio that is neither 0 nor 1 (%v)", sawAutojunk, sawNonTrivial)
	}
}

func TestPyRoundIsCPythonsRoundBitForBit(t *testing.T) {
	// 🔴 A MUTANT CHANGING THE DIGIT COUNT FROM 3 TO 2 SURVIVED THE RENDERED BATTERY,
	// because engineering a search score that lands on a `.xx5` boundary through the
	// scorer is not something a fixture can do reliably. Measuring the function is.
	//
	// The composition under test is "format correctly to N places, then parse back", which
	// is what CPython does; `math.Round(x*1000)/1000` is NOT it and disagrees on ordinary
	// inputs. The table is loaded with `.xx5` boundaries for that reason.
	fx := loadFixture(t)
	if len(fx.PyRoundCases) == 0 {
		t.Fatal("no rounding cases declared, so this test is vacuous")
	}
	moved := 0
	for _, row := range fx.PyRoundCases {
		in, err := strconv.ParseFloat(row.ValueHex, 64)
		if err != nil {
			t.Fatal(err)
		}
		want, err := strconv.ParseFloat(row.RoundedHex, 64)
		if err != nil {
			t.Fatal(err)
		}
		got := pyRound(in, row.Digits)
		if got != want {
			t.Errorf("pyRound(%s, %d) = %s, CPython says %s",
				row.ValueHex, row.Digits, strconv.FormatFloat(got, 'x', -1, 64), row.RoundedHex)
		}
		if in != want {
			moved++
		}
	}
	// The POSITIVE CONTROL: a table whose every value is already rounded would pass with
	// the function replaced by the identity.
	if moved == 0 {
		t.Fatal("no case in the table actually ROUNDS, so the identity function would pass")
	}
}

func TestACLIConsumesTheReportWithoutAServer(t *testing.T) {
	// 🔴 THIS IS THE P2 CONTRACT, EXERCISED RATHER THAN ASSERTED. The pod and the CLI must
	// run ONE renderer, so the package has to be consumable by a caller that has no HTTP
	// request, no server config and no handler to turn an error into a status. This walks
	// exactly that path: the report, its bytes with the CLI's OWN header lines, and the exit
	// decision with its warning sentence.
	//
	// 🔴 AND `extraHeader` IS OTHERWISE DEAD. The pod passes nil — its `/data` has no sync
	// stamp to print — so without this the parameter is a declaration nothing honours, and
	// the day the CLI passes one is the day its POSITION is discovered to be wrong.
	fx := loadFixture(t)
	root := buildFixtureStore(t, fx)

	rep, err := Recall(root, RecallOptions{
		Scope: "alpha-notes", Limit: DefaultEntryLimit, Mode: DefaultMode, Page: 1,
	}, store.Unrestricted())
	if err != nil {
		t.Fatal(err)
	}
	stamp := []string{"  read store: /cache/subsystem-store", "  synced: 2000-01-04T00:00:00Z"}
	text := rep.RenderText(fx.Host, stamp)
	code, warning := ExitFor(rep.Status, rep.Scope+"/", rep.Malformed)

	if code != 0 || warning != "" {
		t.Fatalf("a readable scope exits 0 with nothing to warn about: %d %q", code, warning)
	}
	// The extra lines land in the HEADER BLOCK — after the host line and BEFORE the caveat —
	// which is the whole reason the parameter exists rather than the caller prepending its
	// own text.
	lines := strings.Split(text, "\n")
	if len(lines) < 6 {
		t.Fatalf("too few lines to check the header block:\n%s", text)
	}
	if !strings.HasPrefix(lines[2], "  host: ") {
		t.Fatalf("line 3 should be the host line, got %q", lines[2])
	}
	if lines[3] != stamp[0] || lines[4] != stamp[1] {
		t.Fatalf("the extra header must sit between the host line and the caveat:\n%q\n%q",
			lines[3], lines[4])
	}
	if !strings.HasPrefix(lines[5], "  caveat: ") {
		t.Fatalf("the caveat must follow the extra header, got %q", lines[5])
	}
	// And the same report renders WITHOUT them, byte-identical apart from those two lines —
	// so the parameter adds and never reflows.
	bare := rep.RenderText(fx.Host, nil)
	if withoutStamp := strings.Replace(text, stamp[0]+"\n"+stamp[1]+"\n", "", 1); withoutStamp != bare {
		t.Fatalf("the extra header must be purely additive")
	}

	// The search half of the same contract, including the `*-unreachable` exit and its
	// sentence — the one output a CLI has to forward to its own stderr.
	sr, err := Search(root, SearchOptions{
		Scope: "rubble-heap", Query: "lease", Context: ContextBullet,
		Threshold: DefaultThreshold, MaxHits: DefaultMaxHits,
	}, store.Unrestricted())
	if err != nil {
		t.Fatal(err)
	}
	searchCode, searchWarning := ExitFor(sr.Status, sr.Label(), sr.Malformed)
	if searchCode != 3 {
		t.Fatalf("a scope nothing could be read from exits 3, got %d", searchCode)
	}
	if !strings.HasPrefix(searchWarning, "subsystem-recall: search-unreadable: all 2 entry files under `rubble-heap/` are MALFORMED") {
		t.Fatalf("the warning is the reader's own sentence: %q", searchWarning)
	}
	if !strings.Contains(sr.RenderText(fx.Host, stamp), stamp[1]) {
		t.Fatal("the search renderer takes the same extra header")
	}
}

func TestTheNearMissScoreKeepsThreeDecimals(t *testing.T) {
	// 🔴 THE RENDERED BYTES CANNOT SEE THIS, AND A MUTANT PROVED IT. `pyRound(score, 3)` at
	// the call site was changed to `2` and the whole 49-case rendered battery stayed green,
	// because the near miss is PRINTED with two decimals — `0.333` and `0.33` both format to
	// `0.33`, and the suggested threshold (`score - 0.01`) formats the same too. The digit
	// count is a property of the STORED value, so it is asserted on the stored value.
	//
	// It is not unobservable in general: the oracle's `--json` payload emits this number
	// unrounded-by-the-formatter, so a JSON surface — which P2 owes — would show it. Until
	// then this is the assertion that keeps the constant honest.
	fx := loadFixture(t)
	root := buildFixtureStore(t, fx)
	rep, err := Search(root, SearchOptions{
		// Three tokens, ONE of which matches: the mean is exactly 1/3, so a three-place
		// rounding keeps a non-zero third decimal and a two-place one cannot.
		Scope: "alpha-notes", Query: "nginx zzzzqqqq wwwwqqqq",
		Threshold: DefaultThreshold, MaxHits: DefaultMaxHits, Context: ContextBullet,
	}, store.Unrestricted())
	if err != nil {
		t.Fatal(err)
	}
	if rep.BestBelow == nil {
		t.Fatal("no near miss was reported, so this test is vacuous")
	}
	// `round(1/3, 3)` in CPython. Written as the literal rather than derived from pyRound,
	// which would be asserting that the function agrees with itself.
	if rep.BestBelow.Score != 0.333 {
		t.Fatalf("near-miss score %v, want 0.333 — three decimals, as CPython rounds it",
			rep.BestBelow.Score)
	}
	// And the control that names WHY the literal is 0.333 and not 0.33: the two differ, so
	// the digit count is doing something.
	if pyRound(rep.BestBelow.Score, 2) == rep.BestBelow.Score {
		t.Fatal("the score is unchanged by a two-place rounding, so this case cannot tell " +
			"a three-place rounding from a two-place one")
	}
}

func TestTheListingTieBreakDoesNotDependOnTheCALLERSOrder(t *testing.T) {
	// 🔴 A MUTANT DELETING THE REF TIE-BREAK — `return false` on an mtime tie — SURVIVED
	// the whole rendered battery, and the reason is the SEAM rather than the function:
	// `Recall` always hands this a ref-ASCENDING slice, and a stable sort with no tie-break
	// preserves that order, so the two agree for every caller inside this package. They do
	// not agree for a caller that hands over an unsorted slice, which the CLI (P2) is free
	// to be. So the tie-break is pinned HERE, against an input in the WRONG order, which is
	// the only input that can see it.
	entries := []RecalledEntry{
		{Ref: "zulu", MTime: 100.0},
		{Ref: "alpha", MTime: 100.0},
		{Ref: "mike", MTime: 200.0},
	}
	got := ListingOrder(entries)
	want := []string{"mike", "alpha", "zulu"}
	for i, ref := range want {
		if got[i].Ref != ref {
			t.Fatalf("order: got %s, want %v", refsOf(got), want)
		}
	}
	// And the mtime axis still dominates, so this is not merely an alphabetical sort.
	if got[0].Ref != "mike" {
		t.Fatalf("newest-first must still hold: %s", refsOf(got))
	}
}

func refsOf(entries []RecalledEntry) string {
	refs := make([]string, 0, len(entries))
	for _, e := range entries {
		refs = append(refs, e.Ref)
	}
	return strings.Join(refs, ",")
}

func TestTheFixtureCoversTheSHAPESTheCorpusCannotSend(t *testing.T) {
	// 🔴 A LEDGER OVER THE FIXTURE'S OWN OUTPUT, NOT OVER ITS CASE IDS. A list of ids would
	// pass as soon as somebody named a case; what has to hold is that the RENDERED BYTES
	// somewhere in this fixture actually exercise each branch. So each row below names a
	// string only that branch can produce, and the check fails when the set SHRINKS —
	// which is what happens when a fixture row is quietly weakened or deleted.
	fx := loadFixture(t)
	all := strings.Builder{}
	for _, tc := range fx.Cases {
		all.WriteString(strings.Join(tc.Expect.TextLines, "\n"))
		all.WriteString("\n")
	}
	rendered := all.String()
	for _, row := range []struct{ branch, marker string }{
		{"the OPEN badge", "🔴 1 OPEN"},
		{"the NEAR-MISS badge", "🔴 1 NEAR-MISS"},
		{"the UNVERIFIABLE badge", "⚠ 1 UNVERIFIABLE"},
		{"the missing-heading badge, naming BOTH counted headings", "🔴 NO Pointers, Nuance / work-history"},
		{"the task badge", "🔗 2 tasks"},
		{"the task refs in a body", "    tasks: github:"},
		{"a sensitivity the schema HONOURED", "sensitivity=public"},
		{"a sensitivity the fail-safe OVERRODE", "(declared: internal)"},
		{"the three-badge caveat clause", "Three further badges say"},
		{"the fill-in notice for a bare entry", "the entry exists but has not been filled in"},
		{"the missing-section body notice", "section)"},
		{"the no-parsable-What-it-is notice", "no parsable `## What it is`"},
		{"a malformed entry BESIDE readable ones", "READABLE entr"},
		{"the malformed-elsewhere count", "further malformed entr"},
		{"list mode's withdrawn completeness claim", "NOT the complete index"},
		{"list mode's clean completeness claim", "the complete index for"},
		{"the digest's own omission notice", "LISTED ABOVE but NOT shown in full"},
		{"full mode's --limit truncation notice", "NOT shown (--limit"},
		{"the paginated index header", "of the index for"},
		{"the page-past-the-end block", "IS PAST THE END"},
		{"the more-entries-on-later-pages notice", "NOT LISTED on this page"},
		{"an ambiguous ref", "AMBIGUOUS REF"},
		{"a qualified ref absence", "may name one of them"},
		{"an unqualified ref absence", "Nothing recorded under that name yet"},
		{"scope-empty", "exists but holds no entries"},
		{"scope-absent", "NOTHING RECORDED YET ON THIS HOST"},
		{"scope-unreadable", "NOTHING COULD BE READ"},
		{"search-unreadable's extra sentence", "was never run against anything"},
		{"a name-only search hit", "entry-name]"},
		{"the difflib fuzzy rung", "[0.95 line]"},
		{"the prefix rung", "[0.92 line]"},
		{"the substring rung", "[0.85 line]"},
		{"a sub-threshold near miss with its score", "The closest candidate was"},
		{"an absent term, which is a DIFFERENT sentence", "No candidate scored above zero"},
		{"the --max-hits truncation notice", "NOT shown (--max-hits"},
		{"a raw ±N context window", "context=±2 raw lines"},
		{"a zero-line context window", "context=±0 raw lines"},
		{"an all-scopes search", "scope=(all scopes)"},
		{"a scope with no entries in the searched set", "(none)"},
	} {
		if !strings.Contains(rendered, row.marker) {
			t.Errorf("no fixture case renders %s (looked for %q). The fixture's whole value "+
				"is covering what the HTTP corpus cannot send; a branch that dropped out of "+
				"it is a branch nothing measures.", row.branch, row.marker)
		}
	}
}
