package ui

import (
	"strings"

	g "maragu.dev/gomponents"
	c "maragu.dev/gomponents/components"
	h "maragu.dev/gomponents/html"

	"github.com/ZacxDev/cairn/internal/control"
)

// 🔴 EVERY CLASS NAME THIS FILE RENDERS IS A SEMANTIC NAME DEFINED IN `tailwind.css`, AND
// A RAW TAILWIND UTILITY HERE WOULD SIMPLY NOT WORK. The generator scans NOTHING — the
// stylesheet is compiled from `tailwind.css` alone — so `h.Class("flex gap-2")` would
// render a class the stylesheet has no rule for, silently, with every test still green.
//
// ⚠ AN EARLIER DRAFT DID CARRY RAW UTILITIES HERE, BEHIND AN `@source "./*.go"`, AND THAT
// SCAN WAS THE DEFECT. Tailwind's extractor reads the whole file including COMMENTS, and
// this package's comments are dense by house rule: six utilities were generated into
// `app.css` out of ordinary English (`table`, `visible`, `fixed`, `static`, `hidden`,
// `sticky`) with no `Class()` literal anywhere, and rewording one comment line changed the
// generated bytes — turning a build gate red on a comment-only commit with a message that
// blamed a hand-edit. `tailwind.css`'s own header records the measurement.

// Page is the one page Phase A renders.
//
// 🔴 EVERY USER STRING GOES THROUGH `g.Text` OR THROUGH A QUOTED ATTRIBUTE VALUE,
// AND NOTHING GOES THROUGH `g.Raw`. See this package's doc comment for the measured
// scope of gomponents' escaper and for the one place it is NOT enough.
//
// 🔴 PRECONDITION: `scopes` IS THE RESULT OF AN AUTHORITY QUERY, EVEN WHEN IT IS
// EMPTY. The empty branch below renders a sentence that distinguishes "your
// credential may see nothing" from "the store is empty", and it can only say that if
// somebody asked. Handing this function `nil` without calling [Source.Visible] makes
// it assert an answer nobody obtained — which a route on this server once did.
// `TestEveryContentRouteConsultsTheAuthority` pins that every route in the table
// ASKS, across the whole dispatch table rather than at the one call site. It does
// NOT pin that the answer is what reaches this function — a handler that called
// [Source.Visible] and then passed `nil` anyway would satisfy it.
// The `csrf` argument is the token from [csrfTokenFor] — empty for a caller with no
// session cookie, in which case the sign-out control is not rendered at all. A button
// that is present and cannot work is worse than one that is absent: it teaches a user
// that sign-out is unreliable.
func Page(viewer string, scopes []Scope, csrf string) g.Node {
	return c.HTML5(c.HTML5Props{
		Title:    "cairn",
		Language: "en",
		Head:     []g.Node{stylesheetLink()},
		Body: []g.Node{
			h.Header(
				h.Class("page-header"),
				h.H1(g.Text("cairn")),
				// The viewer's display name is USER TEXT: it comes from a
				// `control.Principal`, which comes from a provisioned user record.
				h.P(h.Class("viewer"), g.Text("signed in as "+viewer)),
				g.If(csrf != "", signOutForm(csrf)),
			),
			h.Main(
				h.Class("page-main"),
				g.If(len(scopes) == 0, h.P(h.Class("empty"), g.Text(
					"No scope is visible to this credential. That is an authority "+
						"answer, not an empty store."))),
				g.Map(scopes, scopeSection),
			),
		},
	})
}

// stylesheetLink is the ONE way a page reaches the stylesheet, so all three pages cannot
// end up under different rules.
//
// 🔴 A LINK RATHER THAN AN INLINE `<style>`, AND THE REASON IS NO LONGER THE POLICY THAT
// FIRST FORCED IT. This surface sent `style-src 'self'`, which forbids an inline style
// element in a conforming browser; that header is DELETED (see `writeHTML`), so the
// constraint is gone and the link is a choice. It is kept for two reasons that outlive the
// header: the bytes are now GENERATED by a Tailwind build (see `stylesheet.go`), and
// inlining 28 KB of them into every response would cost that on every page load where a
// route is cached for five minutes; and `TestTheStylesheetIsServedAsItsOwnRoute` pins the
// page's `href` against the route that answers it, which is a relationship an inline
// stylesheet has no way to state. The href is a package constant and never user text;
// `safeHref` is not reached and must not be, for the reason `shareIndex` records about the
// same-origin case.
func stylesheetLink() g.Node {
	return h.Link(h.Rel("stylesheet"), h.Href(StylesheetPath))
}

// signOutForm is a POST, and that is the security property rather than a style choice.
//
// 🔴 A SIGN-OUT LINK WOULD BE A `GET`, AND GATE (6) DOES NOT GUARD `GET`. A state change
// behind a safe method is reachable by any `<img src>` on any page in the world; the
// victim's browser fetches it, the cookie rides along, and they are signed out. Worse,
// the same shape is how a link-prefetcher or an antivirus scanner performs the action by
// accident. `stateChanging` is what decides which requests are guarded, so a state change
// must be spelled with a method that function calls unsafe.
func signOutForm(csrf string) g.Node {
	return h.FormEl(
		h.Class("signout"),
		h.Method("post"),
		h.Action(SignOutPath),
		// The token goes in a QUOTED ATTRIBUTE VALUE, which gomponents escapes. It is
		// base64url and could carry nothing dangerous anyway; it goes through the same
		// path as everything else because a value that is safe today by virtue of its
		// alphabet is safe by accident.
		h.Input(h.Type("hidden"), h.Name(FieldCSRF), h.Value(csrf)),
		h.Button(h.Type("submit"), g.Text("Sign out")),
	)
}

// SignInPage is the way in, and it is the one page this surface renders to an
// unauthenticated caller.
//
// 🔴 IT RENDERS NOTHING THE CALLER SENT. `message` is one of two package constants, never
// a value from the request — the submitted token is not echoed into the field, and the
// refusal does not say which part of the credential was wrong. Both are the same rule
// `internal/api`'s uniform 401 follows, stated where a human is the reader.
//
// ⚠ NEITHER FORM CARRIES A CSRF TOKEN, AND ITS ABSENCE IS A CONSEQUENCE RATHER THAN AN
// OVERSIGHT: there is no session yet, so there is nothing to derive one from. What stands
// in front of login-CSRF — an attacker making a victim's browser sign in as the attacker,
// so the victim's later writes land in the attacker's scopes — is gate (2), the
// same-origin check, which runs on every state-changing request including this one and
// needs no credential to do it. That is why gate (2) exists at all and why it is BEFORE
// authentication rather than after.
//
// 🔴 `provider` RENDERS A SECOND DOOR AND THE FIRST ONE IS NOT REPLACED BY IT. The
// credential form stays whatever the provider button does, for two reasons that are both
// operational rather than aesthetic: it is the door that verified this deployment, and it is
// the only one that works when the identity provider is down — the JWKS is cached and an
// already-issued session survives an outage (`SupabaseJWT`'s own comment measures that), but
// a NEW sign-in through the provider does not. A surface whose only way in depends on a third
// party is a surface with a third party's availability.
func SignInPage(message string, provider bool) g.Node {
	return c.HTML5(c.HTML5Props{
		Title:    "cairn — sign in",
		Language: "en",
		Head:     []g.Node{stylesheetLink()},
		Body: []g.Node{
			h.Header(h.Class("page-header"), h.H1(g.Text("cairn"))),
			h.Main(
				h.Class("signin-main"),
				g.If(message != "", h.P(h.Class("refused"), g.Text(message))),
				// The provider button is FIRST because it is the one door a person can use
				// without holding a secret, and a page that leads with a `password` field
				// teaches somebody to go looking for a credential they do not need.
				g.If(provider, providerForm()),
				h.FormEl(
					h.Class("signin"),
					h.Method("post"),
					h.Action(SignInPath),
					h.Label(h.For("token"), g.Text("Credential")),
					h.Input(
						h.ID("token"),
						// `password`: the value must not be shoulder-readable, and a
						// browser must not offer to remember it as ordinary form text.
						h.Type("password"),
						h.Name(FieldToken),
						h.AutoComplete("off"),
						h.Required(),
					),
					h.Button(h.Type("submit"), g.Text("Sign in")),
				),
			),
		},
	})
}

// providerForm is the GitHub button, and it is a FORM rather than a link.
//
// 🔴 A LINK WOULD BE A `GET`, AND `stateChanging` CALLS `GET` SAFE — so gate (2) would not
// cover it and any `<img src>` in the world, plus every link prefetcher and mail scanner,
// would mint a flight in the visitor's browser and overwrite whatever flight cookie they
// held. That is the same ruling `signOutForm` records, and it is why the start route is a
// POST in the ledger.
//
// ⚠ IT NEEDS NO SCRIPT, WHICH IS THE WHOLE REASON THE FLOW IS PKCE WITH A SERVER-SIDE
// EXCHANGE. The implicit flow was AVAILABLE and was refused: it returns the access token in
// the URL FRAGMENT, which no server ever receives — the page would have to read
// `location.hash` in script and POST it back, which is more code, a second way in, and a
// token in the browser's history.
//
// ⚠ THE AVAILABILITY ARGUMENT USED TO BE PUT AS "`script-src 'self'` WOULD PERMIT A SCRIPT
// SERVED FROM THIS ORIGIN", AND THAT FRAMING IS RETIRED — not because it was wrong, but
// because it implies a policy that no longer exists. The content-security policy was deleted
// in full by operator decision (see `writeHTML`), so script here is not permitted by a
// clause, it is simply unconstrained. Which makes the refusal above WORTH MORE, not less:
// nothing in a browser now stands between this surface and a script, so the only thing
// keeping the flow scriptless is that it was built that way.
func providerForm() g.Node {
	return h.FormEl(
		h.Class("signin-provider"),
		h.Method("post"),
		h.Action(OAuthStartPath),
		h.Button(h.Type("submit"), g.Text("Sign in with "+GitHubLabel)),
	)
}

// ReplicaHonesty is the notice the share flow carries, and it is a CONSTANT so that a
// test can pin the whole of it.
//
// 🔴 IT IS PINNED AS ONE NORMALISED STRING RATHER THAN BY KEYWORD, AND THAT CHOICE IS
// THE GUARD. A test asserting the page contains "cache" or "replica" passes against a
// reworded notice that has quietly dropped a clause — a guard on words is walkable by
// rewording, and the clause most worth dropping is always the one that makes the
// product sound weakest. `TestTheReplicaHonestyNoticeIsPinnedWhole` compares the
// page's rendered text against this constant with HTML ENTITIES RESOLVED and
// WHITESPACE COLLAPSED — the two normalisations that pin the SENTENCE rather than the
// escaper's current spelling of an apostrophe or `gofmt`'s wrapping of this constant.
// So a cosmetic reword FAILS the test. That cost is the price of a machine-readable claim, and it is
// paid deliberately: changing what this surface promises should be an edit somebody
// makes on purpose, in two places, with a reviewer.
//
// 🔴 EVERY CLAUSE IS MEASURED SOMEWHERE ELSE IN THIS TREE, WHICH IS WHY THERE ARE
// EXACTLY THESE THREE:
//
//   - "one replica's answer, read from a cached copy of the authority" —
//     `control.Cache` is stale by design up to its declared `MaxAge`, and `cairn-ui`
//     is a single-replica surface. ⚠ THE EVIDENCE THIS CLAUSE USED TO CITE IS RETRACTED,
//     AND THE CLAUSE ITSELF IS NOT. It read "a stated limit, not an aspiration: there is
//     no `ui-image` derivation and no deployment manifest in this repository" — and both
//     of those are now false: `packages.ui-image` exists and publishes, and the surface is
//     DEPLOYED from a manifest that lives in the operator's GitOps repository rather than
//     here. "No manifest HERE" was never evidence about how many replicas run anywhere;
//     the limit is real and its actual source is `internal/identity/session.go`'s storage
//     decision, which records that the session table pins this surface to one replica and
//     that sticky routing is the intended answer for more.
//   - "another reader gains or loses the scope when their own cache next refreshes" —
//     `control.Cache.ApplyNow`'s promise is explicitly about THIS process and no other.
//   - "does not recall entries already copied" — `ApplyNow` says it in as many words:
//     revoking access stops future syncs and does not recall a replica.
//
// ⚠ WHAT IT DOES NOT SAY, DELIBERATELY: it gives no number. A "within 30 seconds" here
// would be a promise about a refresh interval this package does not own and cannot
// read — the interval is `cmd/cairn-ui`'s, an operator can change it, and a stale
// number in a safety notice is worse than no number. The bound that IS known travels
// per write instead, as [Effect.EffectiveBy].
const ReplicaHonesty = "This page is one replica's answer, read from a cached copy of the " +
	"authority. A change you record here is durable at once, but another reader gains or " +
	"loses the scope when their own cache next refreshes, not at the instant you click. And " +
	"revoking a share stops future syncs: it does not recall entries already copied onto " +
	"somebody's machine."

// ReadOnlyAuthority is what the page says when this deployment has no journal to
// record a share in.
//
// 🔴 IT NAMES THE CONFIGURATION RATHER THAN THE SYMPTOM, WHICH IS THE OPPOSITE OF THIS
// SURFACE'S UNIFORM-REFUSAL RULE AND CORRECT HERE. Everything else this server refuses
// is refused without a reason, because a reason that reaches the wire is an enumeration
// API. This sentence discriminates nothing — it is identical for every caller, every
// scope and every request — and the alternative is an operator who mounted the wrong
// volume hunting a permission problem that does not exist.
//
// ⚠ IT IS THE TOKEN-FILE DEPLOYMENT'S NORMAL STATE, NOT AN ERROR. `internal/control/
// tokenfile` grants no `admin` verb to anybody by design — its own comment says the
// token file "has no sharing to administer" — so on such a deployment the share flow
// is a READ surface, and this sentence is what makes that legible rather than puzzling.
const ReadOnlyAuthority = "This deployment's authority is read-only, so no share can be " +
	"recorded here: cairn-ui was started against a token file rather than a control journal."

// ShareView is everything the share flow renders, assembled by the handler.
//
// 🔴 AN EMPTY `Scope` MEANS THE INDEX — the list of scopes this caller may administer
// — AND NOT "a scope page with nothing on it". The two are different pages and the
// distinction is carried by one field rather than by two types, because both are
// reached through one route and one handler; a second type would be a second place to
// forget the notice.
type ShareView struct {
	// Viewer is the signed-in principal's display name. USER TEXT.
	Viewer string
	// CSRF is the token from `csrfTokenFor`. Empty for a caller with no session
	// cookie, in which case no form is rendered at all — see [Page] for the rule.
	CSRF string
	// Administrable is every scope this caller may share, for the index.
	Administrable []control.NamedScope
	// Scope is the scope under view, or the zero value for the index.
	Scope control.NamedScope
	// Audience is who can see it, from `control.Resolve`.
	Audience []Viewer
	// Revocable is the grant rows this page can take back.
	Revocable []GrantRow
	// Candidates is who this caller may share with.
	Candidates []Subject
	// Outcome is the result of the write that redirected here, or "".
	Outcome string
	// ReadOnly is true when this deployment's authority cannot record a share at all.
	//
	// 🔴 IT IS A PROPERTY OF THE DEPLOYMENT AND IT IS RENDERED ON EVERY SHAPE OF THIS
	// PAGE. A surface that serves the whole share flow and refuses the write only when
	// somebody clicks is the shape every startup refusal in `cmd/cairn-ui` exists
	// against, arriving through a door those refusals cannot watch: this one is a
	// legitimate configuration rather than an error, so it is SAID rather than refused.
	ReadOnly bool
}

// SharePage renders the share flow.
//
// 🔴 THE NOTICE IS RENDERED ON BOTH SHAPES OF THIS PAGE, AND UNCONDITIONALLY. It is
// not attached to the form, because the AUDIENCE LIST is the claim that needs it most:
// "these four principals can see this" is a statement about one replica's cached model
// and reads as a statement about the world. A notice that appeared only when somebody
// was about to write would leave the read — the thing people do far more often —
// unqualified.
func SharePage(v ShareView) g.Node {
	title := "cairn — sharing"
	if v.Scope.Name != "" {
		title = "cairn — sharing " + v.Scope.Name
	}
	return c.HTML5(c.HTML5Props{
		Title:    title,
		Language: "en",
		Head:     []g.Node{stylesheetLink()},
		Body: []g.Node{
			h.Header(
				h.Class("page-header"),
				h.H1(g.Text("cairn")),
				h.P(h.Class("viewer"), g.Text("signed in as "+v.Viewer)),
				g.If(v.CSRF != "", signOutForm(v.CSRF)),
			),
			h.Main(
				h.Class("page-main"),
				// The notice is FIRST, above every answer it qualifies. A caveat under
				// a list is a caveat most readers never reach.
				h.P(h.Class("replica-honesty"), g.Text(ReplicaHonesty)),
				g.If(v.ReadOnly, h.P(h.Class("read-only"), g.Text(ReadOnlyAuthority))),
				g.If(v.Outcome != "", h.P(h.Class("outcome"), g.Text(v.Outcome))),
				g.If(v.Scope.Name == "", shareIndex(v)),
				g.If(v.Scope.Name != "", shareScopeSection(v)),
			),
		},
	})
}

// shareIndex lists the scopes this caller may administer.
func shareIndex(v ShareView) g.Node {
	return h.Section(
		h.Class("share-index"),
		h.H2(g.Text("Scopes you can share")),
		g.If(len(v.Administrable) == 0, h.P(h.Class("empty"), g.Text(
			"No scope is administrable by this credential. That is an authority answer, "+
				"not an empty store."))),
		h.Ul(g.Map(v.Administrable, func(s control.NamedScope) g.Node {
			// 🔴 THE LINK IS BUILT FROM A CONSTANT PATH AND AN ID, NEVER FROM THE
			// DISPLAY NAME. A scope name is USER TEXT and a name-keyed URL would put it
			// in a query position; the id is minted by `control.NewID` over an alphabet
			// chosen to be safe in a URL without quoting, which is exactly the property
			// being relied on here. `safeHref` is not reached and must not be — it
			// ALLOWLISTS absolute http(s), and this is a same-origin path.
			href := SharePath + "?" + QueryScope + "=" + string(s.ID)
			return h.Li(h.A(h.Href(href), g.Text(s.Name)))
		})),
	)
}

// shareScopeSection is one scope's page: who can see it, what can be taken back, and the
// form that adds somebody.
func shareScopeSection(v ShareView) g.Node {
	return h.Section(
		h.Class("share-scope"),
		h.H2(g.Text("Sharing "+v.Scope.Name)),

		h.H3(g.Text("Who has access to this")),
		g.If(len(v.Audience) == 0, h.P(h.Class("empty"), g.Text("Nobody has access to this scope."))),
		h.Ul(h.Class("audience"), g.Map(v.Audience, audienceItem)),

		h.H3(g.Text("Shares you can take back")),
		// 🔴 THIS SENTENCE IS WHY THE TWO LISTS ARE SEPARATE RATHER THAN ONE LIST WITH
		// SOME BUTTONS MISSING. A reader who revokes every row here and expects the
		// audience to empty has misunderstood the model; saying it once, where they are
		// looking, is cheaper than the support conversation.
		h.P(h.Class("note"), g.Text(
			"Only grants appear here. Somebody who reaches this scope through membership "+
				"of the project that owns it keeps it after every grant below is revoked.")),
		g.If(len(v.Revocable) == 0, h.P(h.Class("empty"), g.Text("No grant names this scope."))),
		h.Ul(h.Class("grants"), g.Map(v.Revocable, func(row GrantRow) g.Node {
			return revocableItem(row, v.CSRF)
		})),

		h.H3(g.Text("Share with")),
		g.If(v.CSRF == "", h.P(h.Class("note"), g.Text(
			"This credential has no browser session, so no form is rendered. Sign in to share."))),
		g.If(v.CSRF != "", shareForm(v)),
	)
}

func audienceItem(a Viewer) g.Node {
	return h.Li(
		h.Class("viewer-row"),
		h.Span(h.Class("who"), g.Text(a.Display)),
		h.Span(h.Class("kind"), g.Text(string(a.Kind))),
		h.Span(h.Class("verbs"), g.Text(a.Verbs)),
		g.If(a.ByMembership, h.Span(h.Class("via"), g.Text("via project membership"))),
	)
}

// revocableItem renders one grant and its revoke button.
//
// 🔴 THE BUTTON IS A `POST` FOR THE REASON `signOutForm` IS, AND THE STAKE IS HIGHER
// HERE. A revoke behind a `GET` is reachable by any `<img src>` in the world, and a
// link-prefetcher would perform it by accident — silently withdrawing somebody's
// access because a reader hovered a link.
func revocableItem(row GrantRow, csrf string) g.Node {
	return h.Li(
		h.Class("grant-row"),
		h.Span(h.Class("who"), g.Text(row.Subject.Display)),
		h.Span(h.Class("kind"), g.Text(string(row.Subject.Kind))),
		h.Span(h.Class("verbs"), g.Text(row.Verbs)),
		h.Span(h.Class("at"), g.Text(row.GrantedAt)),
		g.If(csrf != "", h.FormEl(
			h.Class("revoke"),
			h.Method("post"),
			h.Action(UnsharePath),
			h.Input(h.Type("hidden"), h.Name(FieldCSRF), h.Value(csrf)),
			h.Input(h.Type("hidden"), h.Name(FieldGrant), h.Value(string(row.ID))),
			h.Button(h.Type("submit"), g.Text("Revoke")),
		)),
	)
}

// shareForm is the grant form.
//
// 🔴 THE RECIPIENT IS A `select` OVER `Candidates`, NOT A FREE-TEXT FIELD, AND THAT IS
// THE SAME DECISION `ControlSharing.Candidates` DOCUMENTS ONE LEVEL DOWN. A free-text
// id or email would make this form an existence oracle: type an address, learn from
// the refusal whether that person has an account here. A closed list cannot answer a
// question the caller could not already answer.
//
// ⚠ THE HANDLER RE-VALIDATES THE CHOICE AGAINST THE SAME LIST. A `select` constrains a
// browser, not an HTTP client, and this form's whole purpose is to be posted to.
func shareForm(v ShareView) g.Node {
	if len(v.Candidates) == 0 {
		return h.P(h.Class("empty"), g.Text(
			"There is nobody this credential can share with. Sharing is offered with the "+
				"people and projects you already share a project with; reaching anybody "+
				"else needs an invite, which this surface does not yet have."))
	}
	return h.FormEl(
		h.Class("share"),
		h.Method("post"),
		h.Action(SharePath),
		h.Input(h.Type("hidden"), h.Name(FieldCSRF), h.Value(v.CSRF)),
		h.Input(h.Type("hidden"), h.Name(FieldScope), h.Value(string(v.Scope.ID))),
		h.Label(h.For("subject"), g.Text("Share with")),
		h.Select(
			h.ID("subject"),
			h.Name(FieldSubject),
			h.Required(),
			g.Map(v.Candidates, func(s Subject) g.Node {
				return h.Option(h.Value(string(s.ID)), g.Text(s.Display+" ("+string(s.Kind)+")"))
			}),
		),
		h.FieldSet(
			h.Legend(g.Text("Permissions")),
			g.Map(grantableVerbs, func(vb control.Verb) g.Node {
				return h.Label(
					h.Input(
						h.Type("checkbox"),
						h.Name(FieldVerb),
						h.Value(string(vb)),
						// Read is pre-ticked because a grant with no verb is refused,
						// and a form whose default submission is an error teaches
						// people to ignore the error.
						g.If(vb == control.VerbRead, h.Checked()),
					),
					g.Text(string(vb)),
				)
			}),
		),
		h.Button(h.Type("submit"), g.Text("Share")),
	)
}

// grantableVerbs is what the form offers, in a fixed order.
//
// 🔴 IT IS `control.AllVerbs` RATHER THAN A LIST WRITTEN OUT HERE. A hand-written copy
// would silently stop offering a verb the model gained — a form that cannot express
// part of the authority model, with nothing going red. `admin` IS offered: it is what
// lets a recipient re-share, which is a real thing a person means to do, and leaving it
// out of the form would not take it out of the model.
var grantableVerbs = control.AllVerbs

func scopeSection(s Scope) g.Node {
	return h.Section(
		h.Class("scope"),
		h.H2(g.Text(s.Name)),
		h.Ul(g.Map(s.Entries, entryItem)),
	)
}

// entryItem renders ONE entry. This is the entry-content path the raw-node ban
// names, and every string it touches came out of a file somebody else wrote.
func entryItem(e Entry) g.Node {
	return h.Li(
		h.Class("entry"),
		// 🔴 THE REF IS IN AN ATTRIBUTE VALUE *AND* IN TEXT CONTENT, DELIBERATELY.
		// The two contexts escape through different code in gomponents —
		// `valueAttr` for the first, `Text` for the second — so a page that put user
		// text in only one of them would leave the other's escaping untested here.
		// A `title` attribute is the honest use as well: the ref is often wider than
		// the column.
		h.Span(h.Class("ref"), h.TitleAttr(e.Ref), g.Text(e.Ref)),
		h.Span(h.Class("title"), g.Text(e.Title)),
		g.If(len(e.Aliases) > 0, h.Ul(
			h.Class("aliases"),
			g.Map(e.Aliases, func(a string) g.Node {
				return h.Li(g.Text(a))
			}),
		)),
		g.If(len(e.Tasks) > 0, h.Ul(
			h.Class("tasks"),
			g.Map(e.Tasks, taskItem),
		)),
	)
}

// taskItem is the ONE href position on this page, and the only place [safeHref]
// is reached from.
//
// 🔴 A REF THAT DOES NOT PASS RENDERS AS TEXT RATHER THAN AS A DEAD LINK OR AS
// NOTHING. Dropping it would hide a fact the file carries; rendering `<a href="">`
// would put a clickable element on the page whose target the reader cannot see.
// Plain text is visible, inert, and says what the file says.
func taskItem(ref string) g.Node {
	href, ok := safeHref(ref)
	if !ok {
		return h.Li(h.Class("task refused"), g.Text(ref))
	}
	return h.Li(h.Class("task"), h.A(h.Href(href), g.Text(ref)))
}

// safeHref is the ONE place a URL reaches an href attribute, and it ALLOWLISTS.
//
// 🔴 A DENYLIST IS THE WRONG SHAPE HERE AND THAT IS NOT A STYLE PREFERENCE. The
// set of URL schemes a browser will execute is open — `javascript:`, `data:`,
// `vbscript:`, and whatever a handler registers — so a list of the ones to refuse
// is a list that is wrong the moment it is written. Two schemes are permitted, and
// a third requires an edit here.
//
// 🔴 THE SCHEME TEST IS CASE-INSENSITIVE AND WHITESPACE-STRIPPED BECAUSE BROWSERS
// ARE — AND WITH AN ALLOWLIST THAT PROTECTS THE *PERMIT* SIDE, WHICH IS THE OPPOSITE
// OF WHAT IT WOULD DO IN A DENYLIST. Measured, not reasoned: removing the
// `ToLower` makes `HTTPS://tracker.invalid/…` be REFUSED and changes nothing about
// `JaVaScRiPt:` — which an allowlist rejects at any casing, because it matches no
// permitted prefix however it is spelled. The same for the strip: removing it
// refuses `  https://…`. So neither is what stops the script-scheme attack; the
// allowlist is. What they buy is two real things: a correctly-spelled URL is not
// silently demoted to plain text, and the value written into the href is the
// STRIPPED one, so what the page shows and what the browser resolves are the same
// string. RFC 3986 §3.1 makes a scheme case-insensitive, and the HTML specification
// strips leading and trailing ASCII whitespace — including C0 controls — from a URL
// attribute before resolving it.
//
// ⚠ WHAT THIS DOES NOT CLAIM: it is not a URL validator. A permitted `https://`
// target may still be hostile — it may be a tracking pixel or a phishing page —
// and nothing here says otherwise. What it claims is narrower and is the property
// the escaper cannot supply: no value leaving this function can cause the BROWSER
// to execute the page author's string as code.
func safeHref(raw string) (string, bool) {
	// The HTML URL-attribute strip: ASCII whitespace and C0 controls at both ends.
	trimmed := strings.Trim(raw, "\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\v\f\r\x0e\x0f"+
		"\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f \x7f")
	if trimmed == "" {
		return "", false
	}
	lower := strings.ToLower(trimmed)
	for _, scheme := range allowedSchemes {
		if strings.HasPrefix(lower, scheme) {
			return trimmed, true
		}
	}
	return "", false
}

// allowedSchemes is the whole allowlist. Lowercase, with the separator included so
// that a host literally named `https` cannot pass as a scheme.
//
// 🔴 A RELATIVE URL IS NOT ON THIS LIST, DELIBERATELY. A ref beginning `/` would be
// a same-origin path, which sounds safe and is the shape that lets a store entry
// address any route this binary serves — including ones a later phase adds. The UI
// builds its own internal links from the ledger, never from user text.
var allowedSchemes = []string{"http://", "https://"}
