package ui

import (
	"net/url"
	"strconv"
	"strings"

	g "maragu.dev/gomponents"
	c "maragu.dev/gomponents/components"
	h "maragu.dev/gomponents/html"

	"github.com/ZacxDev/cairn/internal/control"
	"github.com/ZacxDev/cairn/internal/report"
	"github.com/ZacxDev/cairn/internal/store"
)

// 🔴 EVERY CLASS NAME THIS FILE RENDERS IS A SEMANTIC NAME DEFINED IN `tailwind.css`, AND
// A RAW TAILWIND UTILITY HERE WOULD SIMPLY NOT WORK. The generator scans NOTHING — the
// stylesheet is compiled from `tailwind.css` alone — so `h.Class("flex gap-2")` would
// render a class the stylesheet has no rule for. `TestEveryRenderedClassHasARuleInTheStylesheet`
// is what catches that and is the ONLY thing that can: regenerating leaves `app.css`
// byte-identical, so the currency check stays green, and before that test existed the whole
// package did too.
//
// ⚠ AN EARLIER DRAFT DID CARRY RAW UTILITIES HERE, BEHIND AN `@source "./*.go"`, AND THAT
// SCAN WAS THE DEFECT. Tailwind's extractor reads the whole file including COMMENTS, and
// this package's comments are dense by house rule: six utilities were generated into
// `app.css` out of ordinary English (`table`, `visible`, `fixed`, `static`, `hidden`,
// `sticky`) with no `Class()` literal anywhere, and rewording one comment line changed the
// generated bytes — turning a build gate red on a comment-only commit with a message that
// blamed a hand-edit. `tailwind.css`'s own header records the measurement.

// PageView is everything the three BROWSE pages render, assembled by the handler.
//
// 🔴 ONE TYPE FOR THREE PAGES, FOR THE REASON `ShareView` IS ONE TYPE FOR TWO. Each of
// these pages carries the same shell — viewer, sign-out control, breadcrumbs back to the
// root — and every one of them is reached through a handler that has already called
// [Source.Visible]. Three structs would be three places to forget the shell, and the
// breadcrumb trail would be the thing forgotten, because it is the only part that is
// invisible when it is missing rather than wrong.
//
// 🔴 PRECONDITION: `Scopes` IS THE RESULT OF AN AUTHORITY QUERY, EVEN WHEN IT IS EMPTY.
// The empty branch below renders a sentence that distinguishes "your credential may see
// nothing" from "the store is empty", and it can only say that if somebody asked.
// Handing this a `nil` slice without calling [Source.Visible] makes it assert an answer
// nobody obtained — which a route on this server once did.
// `TestEveryContentRouteConsultsTheAuthority` pins that every route in the table ASKS,
// across the whole dispatch table rather than at the one call site. It does NOT pin that
// the answer is what reaches this function — a handler that called [Source.Visible] and
// then passed `nil` anyway would satisfy it.
type PageView struct {
	// Viewer is the signed-in principal's display name. USER TEXT.
	Viewer string
	// CSRF is the token from [csrfTokenFor] — empty for a caller with no session
	// cookie, in which case the sign-out control is not rendered at all. A button that
	// is present and cannot work is worse than one that is absent: it teaches a user
	// that sign-out is unreliable.
	CSRF string
	// Scopes is the WHOLE narrowed answer, on every page. The root renders it as cards;
	// the other two pages pick out of it and still carry it, because the breadcrumb and
	// the navigation page are built from it.
	Scopes []Scope

	// Query is the search box's current value, "" when nothing was asked. USER TEXT,
	// reflected into a form control — see `handlePage` for why that position is
	// different from a reflected banner.
	Query string
	// Results is the answer to Query, nil when there was no query. A non-nil Results
	// with no Hits is a real zero and renders as one; nil means nobody asked.
	Results *SearchResults

	// Scope is the scope under view on the scope and entry pages, nil on the root.
	Scope *Scope
	// Entry is the entry under view on the entry page, nil elsewhere.
	Entry *Entry
}

// Page is the ROOT: every scope this credential may read, as cards, plus the search box.
//
// 🔴 EVERY USER STRING GOES THROUGH `g.Text` OR THROUGH A QUOTED ATTRIBUTE VALUE,
// AND NOTHING GOES THROUGH `g.Raw`. See this package's doc comment for the measured
// scope of gomponents' escaper and for the one place it is NOT enough.
func Page(v PageView) g.Node {
	return shell("cairn", v, nil,
		searchForm(v),
		// 🔴 `g.Iff` AND NOT `g.If`, AND THE DIFFERENCE IS A NIL DEREFERENCE RATHER THAN
		// A STYLE CHOICE. `g.If(cond, node)` takes a NODE, so Go evaluates the argument
		// before the condition is ever consulted — `searchResults(v)` would run, and
		// dereference `v.Results`, on every page load that carried no query. Measured as a
		// segfault in the route walk, not reasoned about. `g.Iff` takes a closure and
		// calls it only when the condition holds. Every `g.If` below is safe because its
		// argument dereferences nothing; any new one that reads a pointer must be `g.Iff`.
		g.Iff(v.Results != nil, func() g.Node { return searchResults(v) }),
		// 🔴 THE CARDS ARE WITHHELD WHILE A QUERY IS IN FORCE, AND THE ALTERNATIVE WAS
		// MEASURED WORSE ON ITS OWN TERMS RATHER THAN ON TASTE. Rendering both puts a
		// full, unfiltered scope list directly under a result list, and the two read as
		// one list: the second half then looks like more results that happen to match
		// nothing. The way back is a link that says so, not a second list nobody asked
		// for.
		g.If(v.Results == nil, g.Group([]g.Node{
			g.If(len(v.Scopes) == 0, h.P(h.Class("empty"), g.Text(
				"No scope is visible to this credential. That is an authority "+
					"answer, not an empty store."))),
			g.If(len(v.Scopes) > 0, h.Div(h.Class("scope-grid"), g.Map(v.Scopes, scopeCard))),
			g.If(len(v.Scopes) > 0, rootLegend()),
		})),
	)
}

// NavigatePage is what `/scope` and `/entry` answer when the request NAMED NOTHING.
//
// 🔴 IT IS A 200 AND NOT A REFUSAL, AND THE DISCRIMINATOR IS WHETHER THE CALLER NAMED
// SOMETHING. A refusal on this surface is uniform because distinguishing "no such scope"
// from "not yours" would enumerate the store — but a request carrying no id at all has
// asked about no scope, so there is nothing for a uniform refusal to protect and nothing
// the answer can leak. What it gets instead is the thing a person who landed here wants:
// the list of scopes they can reach, which is also the breadcrumb parent of both pages.
//
// ⚠ IT IS DELIBERATELY NOT THE ROOT PAGE. Two rows rendering one page is the shape
// `routes` deleted `GET /entries` for. This is a short list of links with no cards, no
// counts and no search box — a navigation answer, not a second copy of the root.
func NavigatePage(v PageView) g.Node {
	return shell("cairn", v, nil,
		h.Section(
			h.Class("card"),
			h.H2(g.Text("Pick a scope")),
			h.P(h.Class("note"), g.Text(
				"This address names no scope, so there is nothing to show yet. "+
					"These are the scopes this credential can read.")),
			g.If(len(v.Scopes) == 0, h.P(h.Class("empty"), g.Text(
				"No scope is visible to this credential. That is an authority "+
					"answer, not an empty store."))),
			g.If(len(v.Scopes) > 0, h.Ul(h.Class("scope-links"), g.Map(v.Scopes, func(s Scope) g.Node {
				return h.Li(scopeLink(s))
			}))),
		),
	)
}

// ScopePage is ONE scope's entry list.
func ScopePage(v PageView) g.Node {
	s := *v.Scope
	return shell("cairn — "+s.Name, v, []crumb{{Label: s.Name}},
		h.Section(
			h.Class("card"),
			h.H2(g.Text(s.Name)),
			h.P(h.Class("card-what"), g.Text(scopeWhat)),
			scopeStats(s),
			g.If(len(s.Entries) == 0, h.P(h.Class("empty"), g.Text(
				"This scope holds no readable entry. That is what the index says about "+
					"this scope, not what your credential is allowed to see: a scope you "+
					"could not read would not be addressable from here at all."))),
			g.If(len(s.Entries) > 0, h.Ul(h.Class("entry-list"), g.Map(s.Entries, func(e Entry) g.Node {
				return entryRow(s, e)
			}))),
			malformedBlock(s),
		),
		scopeLegend(),
	)
}

// EntryPage is ONE entry: the sections its file carries and the line items under the
// journal heading.
//
// 🔴 THIS IS THE ENTRY-CONTENT PATH THE RAW-NODE BAN NAMES, AND IT IS THE WIDEST ONE ON
// THIS SURFACE. Until this page existed an entry's BODY never reached a browser at all —
// only its ref, title, aliases and task refs did. Every string below came out of a
// markdown file somebody else wrote, in both text and attribute positions, and
// `entryRow`'s comment records why the two contexts have to be exercised separately.
func EntryPage(v PageView) g.Node {
	s, e := *v.Scope, *v.Entry
	return shell("cairn — "+e.Ref, v,
		[]crumb{{Label: s.Name, Href: scopeHref(s)}, {Label: e.Ref}},
		h.Section(
			h.Class("card"),
			h.H2(g.Text(e.Ref)),
			h.P(h.Class("card-what"), g.Text(entryWhat)),
			provenance(s, e),
			entryCounts(e),
			g.If(len(e.Aliases) > 0, labelledList("Aliases", "the `aliases:` front-matter key, as written",
				h.Ul(h.Class("aliases"), g.Map(e.Aliases, plainItem)))),
			g.If(len(e.Tasks) > 0, labelledList("Tasks", "the `tasks:` front-matter key, as written",
				h.Ul(h.Class("tasks"), g.Map(e.Tasks, taskItem)))),
			g.If(len(e.Sections) == 0, h.P(h.Class("empty"), g.Text(
				"This entry carries none of the headings a reader surfaces. The file exists "+
					"and the loader accepted it; it simply has no `## What it is`, "+
					"`## Pointers` or `## Nuance / work-history` section in it."))),
			g.Map(e.Sections, sectionBlock),
			missingBlock(e),
		),
		entryLegend(),
	)
}

// crumb is one step of the breadcrumb trail. An empty `Href` is the CURRENT page, which
// renders as text rather than as a link to itself.
type crumb struct {
	Label string
	Href  string
}

// shell is the one page frame, so three pages cannot end up with three headers.
//
// 🔴 THE BREADCRUMB IS PART OF THE FRAME RATHER THAN PER PAGE, BECAUSE A MISSING WAY BACK
// IS INVISIBLE. Two levels of drill-down with no trail is the standard failure of this
// information architecture: every page looks complete, and the only symptom is a reader
// reaching for the browser's back button on a surface that could have told them where
// they were. Putting it here means a page added later gets it without anybody remembering.
func shell(title string, v PageView, crumbs []crumb, body ...g.Node) g.Node {
	return c.HTML5(c.HTML5Props{
		Title:    title,
		Language: "en",
		// ⚠ NO `<meta name="viewport">` IS SPELLED HERE, AND THAT IS A MEASUREMENT RATHER
		// THAN AN OMISSION. Without one a phone lays the page out at ~980 CSS pixels and
		// scales it down, so every responsive rule in `tailwind.css` would apply at a width
		// no reader has — `uiaudit` reports `missing_viewport_meta` for exactly that, and
		// treats it as the reason a narrow capture's `innerWidth` may legitimately exceed
		// the emulated width. `c.HTML5` ALREADY EMITS IT: read out of gomponents v1.3.0's
		// `components/components.go`, which unconditionally puts
		// `<meta name="viewport" content="width=device-width, initial-scale=1">` in the
		// head. A draft of this function added a second identical tag; the walk reported
		// `no-viewport-meta=false` either way, which is how a duplicate would have shipped
		// unnoticed. If gomponents ever drops it, this is the function to spell it in.
		Head: []g.Node{stylesheetLink()},
		Body: []g.Node{
			h.Header(
				h.Class("page-header"),
				// The wordmark is a link to the root on every page, which is the one
				// navigation affordance a reader tries before they read anything.
				h.H1(h.A(h.Href(RootPath), g.Text("cairn"))),
				// The viewer's display name is USER TEXT: it comes from a
				// `control.Principal`, which comes from a provisioned user record.
				h.P(h.Class("viewer"), g.Text("signed in as "+v.Viewer)),
				g.If(v.CSRF != "", signOutForm(v.CSRF)),
			),
			g.If(len(crumbs) > 0, breadcrumbs(crumbs)),
			h.Main(h.Class("page-main"), g.Group(body)),
		},
	})
}

func breadcrumbs(crumbs []crumb) g.Node {
	return h.Nav(
		h.Class("crumbs"),
		// The trail always starts at the root, so the first step is spelled here rather
		// than by every caller.
		h.A(h.Class("crumb"), h.Href(RootPath), g.Text("All scopes")),
		g.Map(crumbs, func(c crumb) g.Node {
			if c.Href == "" {
				return h.Span(h.Class("crumb crumb-here"), g.Text(c.Label))
			}
			return h.A(h.Class("crumb"), h.Href(c.Href), g.Text(c.Label))
		}),
	)
}

// searchForm is a plain `GET` form, and the absence of script is the point.
//
// 🔴 NO JAVASCRIPT, ON A SURFACE WHOSE XSS STORY PARTLY RESTS ON THERE BEING NONE. A
// type-ahead would need a script, a script would need a fetch, and `document.scripts.length`
// would stop being zero — which is a property `uiaudit` measures on every captured page
// precisely so that it cannot drift silently. A `GET` form gives a shareable URL, a working
// back button and a browser-native reload for free, none of which a script version gets
// without writing them.
//
// ⚠ THE ACTION IS THE ROOT PATH, WHICH IS ALSO WHERE A BLANK SUBMISSION LANDS. Submitting an
// empty box is how a reader clears a search, and it arrives as `?q=` — which
// `handlePage` trims to "" and treats as no query at all.
func searchForm(v PageView) g.Node {
	return h.FormEl(
		h.Class("searchbar"),
		h.Method("get"),
		h.Action(RootPath),
		h.Label(h.For("q"), g.Text("Search entries")),
		h.Input(
			h.ID("q"),
			// `search` rather than `text`: a browser renders a clear affordance and an
			// on-screen keyboard offers a search key. Both are free and neither needs a
			// script.
			h.Type("search"),
			h.Name(QueryQuery),
			h.Value(v.Query),
			h.Placeholder("words to look for"),
			h.AutoComplete("off"),
		),
		h.Button(h.Type("submit"), g.Text("Search")),
	)
}

// searchResults renders the scored answer from `internal/report`.
//
// 🔴 A ZERO IS RENDERED AS A READABLE ZERO, WHICH IS `report.SearchReport.BestBelow`'s
// WHOLE REASON FOR EXISTING. "Nothing matched" and "the best candidate fell just under the
// threshold" are different facts with different next actions, and a page that prints one
// blank for both has diagnosed nothing. The searched-scope list is rendered beside it for
// the same reason one level up: a zero over an EMPTY scope set is an authority answer, not
// a statement about the store.
func searchResults(v PageView) g.Node {
	r := *v.Results
	return h.Section(
		h.Class("card results"),
		h.H2(g.Text("Search")),
		h.P(h.Class("card-what"), g.Text(searchWhat)),
		h.P(h.Class("note"), g.Text(searchSummary(r))),
		h.P(h.Class("note"), g.Text("Searched: "+scopeListText(r.ScopesSearched))),
		h.P(h.Class("note"), h.A(h.Href(RootPath), g.Text("Clear the search and show every scope"))),
		g.If(len(r.Hits) == 0 && r.BestBelow != "", h.P(h.Class("empty"), g.Text(
			"Nothing cleared the threshold. The closest entry was `"+r.BestBelow+"` — "+
				"so this is a near miss rather than a store with nothing in it."))),
		g.If(len(r.Hits) == 0 && r.BestBelow == "", h.P(h.Class("empty"), g.Text(
			"Nothing matched, and nothing came close either: no entry in the scopes above "+
				"scored against these words at all."))),
		g.If(len(r.Hits) > 0, h.Ul(h.Class("hits"), g.Map(r.Hits, hitItem))),
	)
}

func hitItem(hit Hit) g.Node {
	return h.Li(
		h.Class("hit"),
		h.P(
			h.Class("hit-where"),
			// The hit LINKS to the entry it came from, which is the whole reason the
			// scope id is carried onto the hunk. A hit that a reader cannot open is a
			// search result they have to go and find by hand.
			entryLinkFor(hit.ScopeID, hit.Ref, hit.Ref),
			h.Span(h.Class("hit-scope"), g.Text(hit.Scope)),
			g.If(hit.Section != "", h.Span(h.Class("hit-section"), g.Text(hit.Section))),
			h.Span(h.Class("hit-score"), g.Text(formatScore(hit.Score))),
			// `entry-name` means the entry's REF or an alias matched and no line did, so
			// the lines below are the entry's best block shown as a worked example rather
			// than the thing that matched. Without it a name-only hit is indistinguishable
			// from a line hit.
			g.If(hit.Basis == report.BasisEntryName,
				h.Span(h.Class("badge badge-quiet"), g.Text("matched the entry name"))),
		),
		h.Pre(h.Class("hit-lines"), h.Code(g.Text(strings.Join(hit.Lines, "\n")))),
	)
}

// scopeCard is ONE scope, as the root page's card.
//
// 🔴 EVERY FIELD ON IT IS LABELLED WITH WHAT IT IS IN THE UNDERLYING STORE, AND THAT IS
// THE WHOLE POINT OF THE CARD RATHER THAN A FLOURISH. The first version of this page
// rendered a bare heading over a list of refs, and the operator's complaint about it was
// exactly that nothing said what the heading WAS or what the list items were. A card
// whose title is unexplained is a card a reader has to guess at, and they will guess it
// is a project, or a file, or a tag.
func scopeCard(s Scope) g.Node {
	return h.Section(
		h.Class("card"),
		h.Div(
			h.Class("card-head"),
			h.H2(scopeLink(s)),
			h.Span(h.Class("kind"), g.Text("scope")),
		),
		h.P(h.Class("card-what"), g.Text(scopeWhat)),
		scopeStats(s),
		g.If(len(s.Entries) > 0, h.Ul(
			h.Class("card-entries"),
			g.Map(cardEntryPreview(s.Entries), func(e Entry) g.Node {
				return h.Li(h.Class("card-entry"), h.Span(h.Class("ref"), g.Text(e.Ref)))
			}),
		)),
		g.If(len(s.Entries) > cardPreview, h.P(h.Class("card-more"), g.Text(
			plural(len(s.Entries)-cardPreview, "more entry", "more entries")+" not shown"))),
		g.If(len(s.Entries) == 0, h.P(h.Class("empty"), g.Text("No readable entry in this scope."))),
		g.If(len(s.Malformed) > 0, h.P(h.Class("card-warn"), g.Text(
			plural(len(s.Malformed), "entry file", "entry files")+" in this scope could not be read"))),
	)
}

// cardPreview is how many entry refs a card lists before it says how many it left out.
//
// ⚠ A FIXED NUMBER, AND THE CARD SAYS WHEN IT TRUNCATED. A card that silently showed the
// first few would read as a complete list of a small scope.
const cardPreview = 5

func cardEntryPreview(entries []Entry) []Entry {
	if len(entries) > cardPreview {
		return entries[:cardPreview]
	}
	return entries
}

// scopeStats is the card's counts, and each one names what it counted.
//
// 🔴 `declared open` RATHER THAN `open`, AND THE WORD IS LOAD-BEARING. The openness
// marker is opt-in: `report.RecalledEntry.OpenCount`'s own comment records that a zero
// means "nothing was declared" and NOT "nothing is open", and every bullet written before
// the marker existed carries none. A badge reading `0 open` over a scope full of
// unfinished work would be a completeness claim this store cannot make.
func scopeStats(s Scope) g.Node {
	return h.P(
		h.Class("card-stats"),
		h.Span(h.Class("stat"), g.Text(plural(len(s.Entries), "entry", "entries"))),
		g.If(s.OpenCount() > 0, h.Span(h.Class("stat stat-open"),
			g.Text(plural(s.OpenCount(), "bullet", "bullets")+" declared open"))),
		g.If(s.OpenCount() == 0, h.Span(h.Class("stat stat-quiet"),
			g.Text("no bullet declares itself open"))),
		g.If(len(s.Malformed) > 0, h.Span(h.Class("stat stat-warn"),
			g.Text(plural(len(s.Malformed), "unreadable file", "unreadable files")))),
	)
}

// entryRow is one entry on the scope page.
func entryRow(s Scope, e Entry) g.Node {
	return h.Li(
		h.Class("entry-row"),
		// 🔴 THE REF IS IN AN ATTRIBUTE VALUE *AND* IN TEXT CONTENT, DELIBERATELY. The
		// two contexts escape through different code in gomponents — `valueAttr` for the
		// first, `Text` for the second — so a page that put user text in only one of them
		// would leave the other's escaping untested here. A `title` attribute is the
		// honest use as well: the ref is often wider than the column. Here it reaches a
		// THIRD position on top of those two — a query parameter inside an href — which
		// `entryHref` percent-encodes rather than escapes.
		h.Span(h.Class("ref"), h.TitleAttr(e.Ref), entryLinkFor(s.ID, e.Ref, e.Ref)),
		h.Span(h.Class("title"), g.Text(e.Title)),
		g.If(e.OpenCount > 0, h.Span(h.Class("badge badge-open"),
			g.Text(plural(e.OpenCount, "OPEN bullet", "OPEN bullets")))),
		g.If(e.NearMissCount > 0, h.Span(h.Class("badge badge-near"),
			g.Text(plural(e.NearMissCount, "near-miss marker", "near-miss markers")))),
		h.Span(h.Class("entry-count"), g.Text(plural(e.BulletCount, "journal bullet", "journal bullets"))),
		g.If(len(e.Aliases) > 0, h.Ul(
			h.Class("aliases"),
			g.Map(e.Aliases, func(a string) g.Node { return h.Li(g.Text(a)) }),
		)),
		g.If(len(e.Tasks) > 0, h.Ul(h.Class("tasks"), g.Map(e.Tasks, taskItem))),
	)
}

// provenance is the entry page's "where did this come from" block.
//
// ⚠ IT NAMES A FILENAME AND A SCOPE, WHICH ARE NOT DEPLOYMENT FACTS. The scope is a name
// the caller already proved they may read and the filename is relative to it; neither is
// a filesystem PATH, and the store root is deliberately not on the page — a path is a
// fact about the deployment rather than about the request, which is the rule
// `handlePage`'s error branch follows.
func provenance(s Scope, e Entry) g.Node {
	return h.Dl(
		h.Class("provenance"),
		h.Dt(h.Class("prov-key"), g.Text("scope")),
		h.Dd(h.Class("prov-val"), g.Text(s.Name)),
		h.Dt(h.Class("prov-key"), g.Text("file")),
		h.Dd(h.Class("prov-val"), g.Text(e.Filename)),
		h.Dt(h.Class("prov-key"), g.Text("service:")),
		h.Dd(h.Class("prov-val"), g.Text(e.Title)),
	)
}

func entryCounts(e Entry) g.Node {
	return h.P(
		h.Class("card-stats"),
		h.Span(h.Class("stat"), g.Text(plural(e.BulletCount, "journal bullet", "journal bullets"))),
		g.If(e.OpenCount > 0, h.Span(h.Class("stat stat-open"),
			g.Text(plural(e.OpenCount, "declared open", "declared open")))),
		g.If(e.NearMissCount > 0, h.Span(h.Class("stat stat-warn"),
			g.Text(plural(e.NearMissCount, "near-miss marker", "near-miss markers")))),
	)
}

// sectionBlock is ONE `##` heading of the file and what sits under it.
//
// 🔴 THE JOURNAL SECTION RENDERS AS LINE ITEMS AND EVERY OTHER SECTION RENDERS AS TEXT,
// AND NEITHER IS MARKDOWN. There is no markdown renderer on this surface and adding one
// would be a second parser to disagree with `internal/store` — plus a new sink for
// attacker-authored markup, which is the one thing this package's whole escaping story is
// built around. A `<pre>` shows the file's own bytes: what the writer typed, wrapped the
// way they wrapped it, with no interpretation to get wrong.
func sectionBlock(s Section) g.Node {
	return h.Section(
		h.Class("entry-section"),
		h.H3(h.Class("section-head"), g.Text(s.Heading)),
		g.If(len(s.Bullets) == 0 && s.Body == "", h.P(h.Class("empty"), g.Text(
			"Present and empty. The heading is in the file with nothing under it, which "+
				"is a different fact from the heading being absent."))),
		g.If(len(s.Bullets) == 0 && s.Body != "", h.Pre(h.Class("section-body"), h.Code(g.Text(s.Body)))),
		g.If(len(s.Bullets) > 0, h.Ul(h.Class("bullets"), g.Map(s.Bullets, bulletItem))),
	)
}

// bulletItem is ONE line item.
//
// 🔴 THE BADGE IS DERIVED FROM `store.JournalBullet.OpennessPopulation` AND NEVER FROM A
// SUBSTRING OF THE TEXT, WHICH IS WHAT KEEPS A REAL MARKER DISTINGUISHABLE FROM ONE THAT
// MERELY LOOKS LIKE ONE. A guard — or a renderer — keyed on the WORD `OPEN` is walkable
// by anybody who writes `OPEN` in prose, and it would also miss the case that matters
// most: `store.PopulationNearMiss` is a bullet that TRIED to write a marker and missed
// the grammar, and `report.RecalledEntry.NearMissCount`'s comment records that until it
// was counted separately it was byte-identical to "no marker" on the read surface — the
// badge simply did not render, and a vanishing badge looks like success. So a near miss
// gets its OWN badge, with its own words, and never the open one.
func bulletItem(b Bullet) g.Node {
	return h.Li(
		h.Class("bullet"),
		h.P(
			h.Class("bullet-meta"),
			g.If(b.Date != "", h.Span(h.Class("bullet-date"), g.Text(b.Date))),
			g.If(b.Population == store.PopulationOpen,
				h.Span(h.Class("badge badge-open"), g.Text("OPEN"))),
			g.If(b.Population == store.PopulationNearMiss,
				h.Span(h.Class("badge badge-near"), g.Text("near-miss marker"))),
			g.If(b.Population == store.PopulationResolved,
				h.Span(h.Class("badge badge-quiet"), g.Text("resolved"))),
			g.If(b.Population == store.PopulationUnverifiable,
				h.Span(h.Class("badge badge-near"), g.Text("resolved, no sha"))),
		),
		h.Pre(h.Class("bullet-body"), h.Code(g.Text(b.Text()))),
	)
}

// malformedBlock renders the entry files the loader REFUSED.
//
// 🔴 A BROWSER THAT DROPPED THEM WOULD DISAGREE WITH THE CLI WHILE LOOKING COMPLETE, and
// that is the whole reason this block exists. `store.LoadStore` loads with `Collect`
// because failing closed cost a whole scope over one bad file — measured: 2 good entries
// and 1 bad one served ZERO — and every other reader in this tree renders the collected
// rows. A tidier page that showed only the good entries would be a shorter, wrong store,
// and the reader would have no way to tell.
func malformedBlock(s Scope) g.Node {
	if len(s.Malformed) == 0 {
		return nil
	}
	return h.Div(
		h.Class("malformed"),
		h.H3(g.Text("Unreadable entry files")),
		h.P(h.Class("note"), g.Text(
			"These files are in this scope's directory and the loader refused them. They are "+
				"listed rather than dropped: a page that hid them would look like a complete "+
				"scope that is missing entries.")),
		h.Ul(g.Map(s.Malformed, func(m Malformed) g.Node {
			return h.Li(
				h.Class("malformed-row"),
				h.Span(h.Class("ref"), g.Text(m.Label)),
				h.Span(h.Class("malformed-why"), g.Text(m.Reason)),
			)
		})),
	)
}

// missingBlock names the COUNTED headings this entry does not carry.
//
// ⚠ ABSENT IS NOT EMPTY, and `store.ExtractSections` goes to some trouble to keep the two
// apart: a heading present with nothing under it is PRESENT-AND-EMPTY, which
// `sectionBlock` renders as such. This block is the other case — the section was never
// started — and only one of the two is a reason to go and look somewhere else.
func missingBlock(e Entry) g.Node {
	if len(e.MissingSections) == 0 {
		return nil
	}
	return h.P(h.Class("missing"), g.Text(
		"Not in this file at all: "+strings.Join(e.MissingSections, ", ")+
			". That is different from a heading that is present and empty."))
}

// The three legends. Each answers "what am I looking at" for the page it sits on, in the
// vocabulary of the FILES rather than of this renderer.
//
// 🔴 THEY EXIST BECAUSE THE FIRST VERSION OF THIS SURFACE WAS UNREADABLE FOR A REASON NO
// TEST COULD SEE. Every escaping guard, every authority guard and every route guard was
// green while a reader could not tell what a heading on the page was, what the items
// under it were, or which part of a file any of it came from. That is a real defect and
// prose is the only fix for it — so the prose is here, beside the thing it describes,
// rather than in a README nobody has open while they are looking at the page.
const (
	scopeWhat = "A scope is one directory under the store root. Its entries are the " +
		"`.md` files in it, one file per entry."
	entryWhat = "One entry file. The sections below are its `##` headings, verbatim; " +
		"the line items under the journal heading are its top-level `-` bullets."
	searchWhat = "Scored over every line of every entry the credential can read, by the " +
		"same engine `cairn search` uses — so a word inside a bullet is findable, not " +
		"just a word in a title."
)

func rootLegend() g.Node {
	return legend([][2]string{
		{"card", "one scope — a directory under the store root"},
		{"card title", "the scope's display name, which is also its directory name"},
		{"entries", "how many `.md` files in it the loader accepted"},
		{"declared open", "bullets carrying an `OPEN:` marker, summed over the scope. " +
			"The marker is opt-in, so a zero means nothing was declared rather than nothing is open"},
		{"the refs listed", "the first few entry refs — a ref is the filename without `.md`"},
	})
}

func scopeLegend() g.Node {
	return legend([][2]string{
		{"row", "one entry file in this scope"},
		{"ref", "the filename without `.md`: `<slug>` or `<slug>.<kind>`"},
		{"title", "the `service:` key in the file's front matter"},
		{"journal bullets", "top-level `-` lines under `## Nuance / work-history`"},
		{"OPEN", "a bullet whose first line carries an `OPEN:` marker"},
		{"near-miss marker", "a bullet that tried to write a marker and missed the grammar. " +
			"It is NOT counted as open, and it is the population most likely to hide a stale action"},
	})
}

func entryLegend() g.Node {
	return legend([][2]string{
		{"section", "one `##` heading in the file, shown with the heading text verbatim"},
		{"line item", "one top-level `-` bullet, with every continuation line it carries"},
		{"date", "an ISO date the bullet's first line starts with. Around half of a real " +
			"corpus carries none, so a blank is ordinary rather than a parse failure"},
		{"OPEN / near-miss / resolved", "which of the store's openness populations the " +
			"bullet is in — exactly one, decided by one predicate shared with the CLI"},
	})
}

func legend(rows [][2]string) g.Node {
	return h.Details(
		h.Class("legend"),
		h.Summary(g.Text("What am I looking at?")),
		h.Dl(g.Group(func() []g.Node {
			out := make([]g.Node, 0, len(rows)*2)
			for _, row := range rows {
				out = append(out,
					h.Dt(h.Class("legend-term"), g.Text(row[0])),
					h.Dd(h.Class("legend-def"), g.Text(row[1])),
				)
			}
			return out
		}())),
	)
}

// labelledList is the aliases/tasks pair on the entry page: a heading that says what the
// list IS, then the list.
//
// 🔴 IT TAKES THE BUILT LIST RATHER THAN A CLASS NAME, AND THAT IS A GUARD RATHER THAN A
// SIGNATURE PREFERENCE. An earlier shape took `class string` and called `h.Class(class)`,
// which `collectRenderedClasses` reports as a NON-LITERAL class source — a finding, not a
// skip, because a class name that scan cannot read is a class name nobody can check has a
// rule in the stylesheet. Nothing scans this package to build `app.css`, so an unreadable
// class ships unstyled with every gate green. The literal belongs at the call site.
func labelledList(heading, what string, list g.Node) g.Node {
	return h.Div(
		h.Class("labelled"),
		h.H3(h.Class("section-head"), g.Text(heading)),
		h.P(h.Class("note"), g.Text(what)),
		list,
	)
}

func plainItem(s string) g.Node { return h.Li(g.Text(s)) }

// scopeLink and entryLinkFor are the ONLY places an internal browse URL is built.
//
// 🔴 THE PATHS ARE CONSTANTS AND THE OPERANDS GO THROUGH `url.Values.Encode`, WHICH IS
// THE HALF `shareIndex` DOES NOT NEED. A scope id is minted by `control.NewID`/
// `control.DerivedID` over an alphabet chosen to be safe in a URL without quoting, so the
// share flow concatenates it directly. An entry REF is not: it is a filename stem out of
// a file somebody else wrote, so it can carry `&`, `#`, a space or a percent sequence, and
// concatenating it would let the file's own name inject a second query parameter.
// `Encode` is the encoder for that position, and it sorts its keys, so the URL a page
// renders for one entry is the same string every time.
//
// ⚠ `safeHref` IS NOT REACHED AND MUST NOT BE, which is `shareIndex`'s ruling for the same
// shape: it ALLOWLISTS absolute http(s), and these are same-origin paths.
func scopeHref(s Scope) string {
	return ScopePath + "?" + url.Values{QueryID: []string{string(s.ID)}}.Encode()
}

func entryHref(scope control.ID, ref string) string {
	return EntryPath + "?" + url.Values{
		QueryScope: []string{string(scope)},
		QueryRef:   []string{ref},
	}.Encode()
}

// scopeLink renders a scope's name as a link, or as plain text when the authority named
// no id for it.
//
// 🔴 AN UNLINKED CARD RATHER THAN A LINK TO `?id=`, AND THE DIFFERENCE IS NOT COSMETIC. A
// scope with no id cannot be addressed, so a link would resolve to `/scope?id=` — which
// `handleScopePage` reads as "named nothing" and answers with the navigation page. A
// reader would click a scope and land on a list of scopes, which reads as a broken link
// rather than as the honest "this one has no address". `pickScope` refuses an empty id for
// the same reason from the other side.
func scopeLink(s Scope) g.Node {
	if s.ID == "" {
		return h.Span(h.Class("card-name"), g.Text(s.Name))
	}
	return h.A(h.Class("card-name"), h.Href(scopeHref(s)), g.Text(s.Name))
}

func entryLinkFor(scope control.ID, ref, label string) g.Node {
	if scope == "" || ref == "" {
		return h.Span(g.Text(label))
	}
	return h.A(h.Href(entryHref(scope, ref)), g.Text(label))
}

// searchSummary is the one sentence that says how much of the answer is on the page.
//
// 🔴 THE TRUNCATION IS STATED. A list that silently stopped at `report.DefaultMaxHits`
// reads as "that is all there is", which is the same defect as a scope card that showed
// the first five refs without saying so.
func searchSummary(r SearchResults) string {
	switch {
	case r.TotalHits == 0:
		return "No match cleared the threshold."
	case r.Omitted > 0:
		return plural(len(r.Hits), "match", "matches") + " shown of " +
			strconv.Itoa(r.TotalHits) + " that cleared the threshold; " +
			strconv.Itoa(r.Omitted) + " not shown."
	default:
		return plural(r.TotalHits, "match", "matches") + " cleared the threshold."
	}
}

// scopeListText renders the searched-scope set, and says so when it is EMPTY rather than
// printing nothing — an empty set is an authority answer.
func scopeListText(scopes []string) string {
	if len(scopes) == 0 {
		return "no scope at all, because this credential can read none. That is an " +
			"authority answer, not an empty store."
	}
	return strings.Join(scopes, ", ")
}

// formatScore renders a hunk score at the precision `internal/report` rounds to.
func formatScore(score float64) string {
	return strconv.FormatFloat(score, 'f', 2, 64)
}

// plural is the one place a count meets its noun, so the pages cannot disagree about
// whether one entry is "1 entries".
func plural(n int, one, many string) string {
	if n == 1 {
		return strconv.Itoa(n) + " " + one
	}
	return strconv.Itoa(n) + " " + many
}

// stylesheetLink is the ONE way a page reaches the stylesheet, so all three pages cannot
// end up under different rules.
//
// 🔴 A LINK RATHER THAN AN INLINE `<style>`, AND THE REASON IS NO LONGER THE POLICY THAT
// FIRST FORCED IT. This surface sent `style-src 'self'`, which forbids an inline style
// element in a conforming browser; that header is DELETED (see `writeHTML`), so the
// constraint is gone and the link is a choice. It is kept for two reasons that outlive the
// header: the bytes are now GENERATED by a Tailwind build (see `stylesheet.go`), and
// inlining 28 KB of them into every response would cost that on every page load where the
// route is cached instead; and `TestTheStylesheetIsServedAsItsOwnRoute` pins the page's
// `href` against the route that answers it, which is a relationship an inline stylesheet has
// no way to state.
//
// 🔴 IT EMITS THE HASHED PATH, AND THAT IS WHAT LICENSES THE YEAR-LONG `immutable` ON THE
// RESPONSE. [StylesheetHashedPath] carries a digest of the bytes it serves, so a theme change
// is a different URL and a browser holding the previous one never asks for it again. Linking
// [StylesheetPath] here instead would be silent: every page would render, every style would
// apply on a cold cache, and a returning visitor would go on applying whatever their cache
// holds for an unversioned URL — which is the failure `stylesheet.go` records.
// `TestNoPageLinksTheUnversionedStylesheetPath` refuses that edit.
//
// ⚠ THE HREF IS A PACKAGE VARIABLE NOW RATHER THAN A CONSTANT, AND IT IS STILL NEVER USER
// TEXT — it is derived at init from bytes that reach the binary through a `//go:embed` and
// from nothing else, so `safeHref` is not reached and must not be, for the reason `shareIndex`
// records about the same-origin case.
func stylesheetLink() g.Node {
	return h.Link(h.Rel("stylesheet"), h.Href(StylesheetHashedPath))
}

// signOutForm is a POST, and that is the security property rather than a style choice.
//
// 🔴 A SIGN-OUT LINK WOULD BE A `GET`, AND GATE (6) DOES NOT GUARD `GET`. A state change
// behind a safe method is reachable by any `<img src>` on any page in the world; the
// victim's browser fetches it, the cookie rides along, and they are signed out. Worse,
// the same shape is how a link-prefetcher or an antivirus scanner performs the action by
// accident. `stateChanging` is what decides which requests are guarded, so a state change
// must be spelled with a method that function calls unsafe.
func signOutForm(csrf string) g.Node {
	return h.FormEl(
		h.Class("signout"),
		h.Method("post"),
		h.Action(SignOutPath),
		// The token goes in a QUOTED ATTRIBUTE VALUE, which gomponents escapes. It is
		// base64url and could carry nothing dangerous anyway; it goes through the same
		// path as everything else because a value that is safe today by virtue of its
		// alphabet is safe by accident.
		h.Input(h.Type("hidden"), h.Name(FieldCSRF), h.Value(csrf)),
		h.Button(h.Type("submit"), g.Text("Sign out")),
	)
}

// SignInPage is the way in, and it is the one page this surface renders to an
// unauthenticated caller.
//
// 🔴 IT RENDERS NOTHING THE CALLER SENT. `message` is one of two package constants, never
// a value from the request — the submitted token is not echoed into the field, and the
// refusal does not say which part of the credential was wrong. Both are the same rule
// `internal/api`'s uniform 401 follows, stated where a human is the reader.
//
// ⚠ NEITHER FORM CARRIES A CSRF TOKEN, AND ITS ABSENCE IS A CONSEQUENCE RATHER THAN AN
// OVERSIGHT: there is no session yet, so there is nothing to derive one from. What stands
// in front of login-CSRF — an attacker making a victim's browser sign in as the attacker,
// so the victim's later writes land in the attacker's scopes — is gate (2), the
// same-origin check, which runs on every state-changing request including this one and
// needs no credential to do it. That is why gate (2) exists at all and why it is BEFORE
// authentication rather than after.
//
// 🔴 `provider` RENDERS A SECOND DOOR AND THE FIRST ONE IS NOT REPLACED BY IT. The
// credential form stays whatever the provider button does, for two reasons that are both
// operational rather than aesthetic: it is the door that verified this deployment, and it is
// the only one that works when the identity provider is down — the JWKS is cached and an
// already-issued session survives an outage (`SupabaseJWT`'s own comment measures that), but
// a NEW sign-in through the provider does not. A surface whose only way in depends on a third
// party is a surface with a third party's availability.
func SignInPage(message string, provider bool) g.Node {
	return c.HTML5(c.HTML5Props{
		Title:    "cairn — sign in",
		Language: "en",
		Head:     []g.Node{stylesheetLink()},
		Body: []g.Node{
			h.Header(h.Class("page-header"), h.H1(g.Text("cairn"))),
			h.Main(
				h.Class("signin-main"),
				g.If(message != "", h.P(h.Class("refused"), g.Text(message))),
				// The provider button is FIRST because it is the one door a person can use
				// without holding a secret, and a page that leads with a `password` field
				// teaches somebody to go looking for a credential they do not need.
				g.If(provider, providerForm()),
				h.FormEl(
					h.Class("signin"),
					h.Method("post"),
					h.Action(SignInPath),
					h.Label(h.For("token"), g.Text("Credential")),
					h.Input(
						h.ID("token"),
						// `password`: the value must not be shoulder-readable, and a
						// browser must not offer to remember it as ordinary form text.
						h.Type("password"),
						h.Name(FieldToken),
						h.AutoComplete("off"),
						h.Required(),
					),
					h.Button(h.Type("submit"), g.Text("Sign in")),
				),
			),
		},
	})
}

// providerForm is the GitHub button, and it is a FORM rather than a link.
//
// 🔴 A LINK WOULD BE A `GET`, AND `stateChanging` CALLS `GET` SAFE — so gate (2) would not
// cover it and any `<img src>` in the world, plus every link prefetcher and mail scanner,
// would mint a flight in the visitor's browser and overwrite whatever flight cookie they
// held. That is the same ruling `signOutForm` records, and it is why the start route is a
// POST in the ledger.
//
// ⚠ IT NEEDS NO SCRIPT, WHICH IS THE WHOLE REASON THE FLOW IS PKCE WITH A SERVER-SIDE
// EXCHANGE. The implicit flow was AVAILABLE and was refused: it returns the access token in
// the URL FRAGMENT, which no server ever receives — the page would have to read
// `location.hash` in script and POST it back, which is more code, a second way in, and a
// token in the browser's history.
//
// ⚠ THE AVAILABILITY ARGUMENT USED TO BE PUT AS "`script-src 'self'` WOULD PERMIT A SCRIPT
// SERVED FROM THIS ORIGIN", AND THAT FRAMING IS RETIRED — not because it was wrong, but
// because it implies a policy that no longer exists. The content-security policy was deleted
// in full by operator decision (see `writeHTML`), so script here is not permitted by a
// clause, it is simply unconstrained. Which makes the refusal above WORTH MORE, not less:
// nothing in a browser now stands between this surface and a script, so the only thing
// keeping the flow scriptless is that it was built that way.
func providerForm() g.Node {
	return h.FormEl(
		h.Class("signin-provider"),
		h.Method("post"),
		h.Action(OAuthStartPath),
		h.Button(h.Type("submit"), g.Text("Sign in with "+GitHubLabel)),
	)
}

// ReplicaHonesty is the notice the share flow carries, and it is a CONSTANT so that a
// test can pin the whole of it.
//
// 🔴 IT IS PINNED AS ONE NORMALISED STRING RATHER THAN BY KEYWORD, AND THAT CHOICE IS
// THE GUARD. A test asserting the page contains "cache" or "replica" passes against a
// reworded notice that has quietly dropped a clause — a guard on words is walkable by
// rewording, and the clause most worth dropping is always the one that makes the
// product sound weakest. `TestTheReplicaHonestyNoticeIsPinnedWhole` compares the
// page's rendered text against this constant with HTML ENTITIES RESOLVED and
// WHITESPACE COLLAPSED — the two normalisations that pin the SENTENCE rather than the
// escaper's current spelling of an apostrophe or `gofmt`'s wrapping of this constant.
// So a cosmetic reword FAILS the test. That cost is the price of a machine-readable claim, and it is
// paid deliberately: changing what this surface promises should be an edit somebody
// makes on purpose, in two places, with a reviewer.
//
// 🔴 EVERY CLAUSE IS MEASURED SOMEWHERE ELSE IN THIS TREE, WHICH IS WHY THERE ARE
// EXACTLY THESE THREE:
//
//   - "one replica's answer, read from a cached copy of the authority" —
//     `control.Cache` is stale by design up to its declared `MaxAge`, and `cairn-ui`
//     is a single-replica surface. ⚠ THE EVIDENCE THIS CLAUSE USED TO CITE IS RETRACTED,
//     AND THE CLAUSE ITSELF IS NOT. It read "a stated limit, not an aspiration: there is
//     no `ui-image` derivation and no deployment manifest in this repository" — and both
//     of those are now false: `packages.ui-image` exists and publishes, and the surface is
//     DEPLOYED from a manifest that lives in the operator's GitOps repository rather than
//     here. "No manifest HERE" was never evidence about how many replicas run anywhere;
//     the limit is real and its actual source is `internal/identity/session.go`'s storage
//     decision, which records that the session table pins this surface to one replica and
//     that sticky routing is the intended answer for more.
//   - "another reader gains or loses the scope when their own cache next refreshes" —
//     `control.Cache.ApplyNow`'s promise is explicitly about THIS process and no other.
//   - "does not recall entries already copied" — `ApplyNow` says it in as many words:
//     revoking access stops future syncs and does not recall a replica.
//
// ⚠ WHAT IT DOES NOT SAY, DELIBERATELY: it gives no number. A "within 30 seconds" here
// would be a promise about a refresh interval this package does not own and cannot
// read — the interval is `cmd/cairn-ui`'s, an operator can change it, and a stale
// number in a safety notice is worse than no number. The bound that IS known travels
// per write instead, as [Effect.EffectiveBy].
const ReplicaHonesty = "This page is one replica's answer, read from a cached copy of the " +
	"authority. A change you record here is durable at once, but another reader gains or " +
	"loses the scope when their own cache next refreshes, not at the instant you click. And " +
	"revoking a share stops future syncs: it does not recall entries already copied onto " +
	"somebody's machine."

// ReadOnlyAuthority is what the page says when this deployment has no journal to
// record a share in.
//
// 🔴 IT NAMES THE CONFIGURATION RATHER THAN THE SYMPTOM, WHICH IS THE OPPOSITE OF THIS
// SURFACE'S UNIFORM-REFUSAL RULE AND CORRECT HERE. Everything else this server refuses
// is refused without a reason, because a reason that reaches the wire is an enumeration
// API. This sentence discriminates nothing — it is identical for every caller, every
// scope and every request — and the alternative is an operator who mounted the wrong
// volume hunting a permission problem that does not exist.
//
// ⚠ IT IS THE TOKEN-FILE DEPLOYMENT'S NORMAL STATE, NOT AN ERROR. `internal/control/
// tokenfile` grants no `admin` verb to anybody by design — its own comment says the
// token file "has no sharing to administer" — so on such a deployment the share flow
// is a READ surface, and this sentence is what makes that legible rather than puzzling.
const ReadOnlyAuthority = "This deployment's authority is read-only, so no share can be " +
	"recorded here: cairn-ui was started against a token file rather than a control journal."

// ShareView is everything the share flow renders, assembled by the handler.
//
// 🔴 AN EMPTY `Scope` MEANS THE INDEX — the list of scopes this caller may administer
// — AND NOT "a scope page with nothing on it". The two are different pages and the
// distinction is carried by one field rather than by two types, because both are
// reached through one route and one handler; a second type would be a second place to
// forget the notice.
type ShareView struct {
	// Viewer is the signed-in principal's display name. USER TEXT.
	Viewer string
	// CSRF is the token from `csrfTokenFor`. Empty for a caller with no session
	// cookie, in which case no form is rendered at all — see [Page] for the rule.
	CSRF string
	// Administrable is every scope this caller may share, for the index.
	Administrable []control.NamedScope
	// Scope is the scope under view, or the zero value for the index.
	Scope control.NamedScope
	// Audience is who can see it, from `control.Resolve`.
	Audience []Viewer
	// Revocable is the grant rows this page can take back.
	Revocable []GrantRow
	// Candidates is who this caller may share with.
	Candidates []Subject
	// Outcome is the result of the write that redirected here, or "".
	Outcome string
	// ReadOnly is true when this deployment's authority cannot record a share at all.
	//
	// 🔴 IT IS A PROPERTY OF THE DEPLOYMENT AND IT IS RENDERED ON EVERY SHAPE OF THIS
	// PAGE. A surface that serves the whole share flow and refuses the write only when
	// somebody clicks is the shape every startup refusal in `cmd/cairn-ui` exists
	// against, arriving through a door those refusals cannot watch: this one is a
	// legitimate configuration rather than an error, so it is SAID rather than refused.
	ReadOnly bool
}

// SharePage renders the share flow.
//
// 🔴 THE NOTICE IS RENDERED ON BOTH SHAPES OF THIS PAGE, AND UNCONDITIONALLY. It is
// not attached to the form, because the AUDIENCE LIST is the claim that needs it most:
// "these four principals can see this" is a statement about one replica's cached model
// and reads as a statement about the world. A notice that appeared only when somebody
// was about to write would leave the read — the thing people do far more often —
// unqualified.
func SharePage(v ShareView) g.Node {
	title := "cairn — sharing"
	if v.Scope.Name != "" {
		title = "cairn — sharing " + v.Scope.Name
	}
	return c.HTML5(c.HTML5Props{
		Title:    title,
		Language: "en",
		Head:     []g.Node{stylesheetLink()},
		Body: []g.Node{
			h.Header(
				h.Class("page-header"),
				h.H1(g.Text("cairn")),
				h.P(h.Class("viewer"), g.Text("signed in as "+v.Viewer)),
				g.If(v.CSRF != "", signOutForm(v.CSRF)),
			),
			h.Main(
				h.Class("page-main"),
				// The notice is FIRST, above every answer it qualifies. A caveat under
				// a list is a caveat most readers never reach.
				h.P(h.Class("replica-honesty"), g.Text(ReplicaHonesty)),
				g.If(v.ReadOnly, h.P(h.Class("read-only"), g.Text(ReadOnlyAuthority))),
				g.If(v.Outcome != "", h.P(h.Class("outcome"), g.Text(v.Outcome))),
				g.If(v.Scope.Name == "", shareIndex(v)),
				g.If(v.Scope.Name != "", shareScopeSection(v)),
			),
		},
	})
}

// shareIndex lists the scopes this caller may administer.
func shareIndex(v ShareView) g.Node {
	return h.Section(
		h.Class("share-index"),
		h.H2(g.Text("Scopes you can share")),
		g.If(len(v.Administrable) == 0, h.P(h.Class("empty"), g.Text(
			"No scope is administrable by this credential. That is an authority answer, "+
				"not an empty store."))),
		h.Ul(g.Map(v.Administrable, func(s control.NamedScope) g.Node {
			// 🔴 THE LINK IS BUILT FROM A CONSTANT PATH AND AN ID, NEVER FROM THE
			// DISPLAY NAME. A scope name is USER TEXT and a name-keyed URL would put it
			// in a query position; the id is minted by `control.NewID` over an alphabet
			// chosen to be safe in a URL without quoting, which is exactly the property
			// being relied on here. `safeHref` is not reached and must not be — it
			// ALLOWLISTS absolute http(s), and this is a same-origin path.
			href := SharePath + "?" + QueryScope + "=" + string(s.ID)
			return h.Li(h.A(h.Href(href), g.Text(s.Name)))
		})),
	)
}

// shareScopeSection is one scope's page: who can see it, what can be taken back, and the
// form that adds somebody.
func shareScopeSection(v ShareView) g.Node {
	return h.Section(
		h.Class("share-scope"),
		h.H2(g.Text("Sharing "+v.Scope.Name)),

		h.H3(g.Text("Who has access to this")),
		g.If(len(v.Audience) == 0, h.P(h.Class("empty"), g.Text("Nobody has access to this scope."))),
		h.Ul(h.Class("audience"), g.Map(v.Audience, audienceItem)),

		h.H3(g.Text("Shares you can take back")),
		// 🔴 THIS SENTENCE IS WHY THE TWO LISTS ARE SEPARATE RATHER THAN ONE LIST WITH
		// SOME BUTTONS MISSING. A reader who revokes every row here and expects the
		// audience to empty has misunderstood the model; saying it once, where they are
		// looking, is cheaper than the support conversation.
		h.P(h.Class("note"), g.Text(
			"Only grants appear here. Somebody who reaches this scope through membership "+
				"of the project that owns it keeps it after every grant below is revoked.")),
		g.If(len(v.Revocable) == 0, h.P(h.Class("empty"), g.Text("No grant names this scope."))),
		h.Ul(h.Class("grants"), g.Map(v.Revocable, func(row GrantRow) g.Node {
			return revocableItem(row, v.CSRF)
		})),

		h.H3(g.Text("Share with")),
		g.If(v.CSRF == "", h.P(h.Class("note"), g.Text(
			"This credential has no browser session, so no form is rendered. Sign in to share."))),
		g.If(v.CSRF != "", shareForm(v)),
	)
}

func audienceItem(a Viewer) g.Node {
	return h.Li(
		h.Class("viewer-row"),
		h.Span(h.Class("who"), g.Text(a.Display)),
		h.Span(h.Class("kind"), g.Text(string(a.Kind))),
		h.Span(h.Class("verbs"), g.Text(a.Verbs)),
		g.If(a.ByMembership, h.Span(h.Class("via"), g.Text("via project membership"))),
	)
}

// revocableItem renders one grant and its revoke button.
//
// 🔴 THE BUTTON IS A `POST` FOR THE REASON `signOutForm` IS, AND THE STAKE IS HIGHER
// HERE. A revoke behind a `GET` is reachable by any `<img src>` in the world, and a
// link-prefetcher would perform it by accident — silently withdrawing somebody's
// access because a reader hovered a link.
func revocableItem(row GrantRow, csrf string) g.Node {
	return h.Li(
		h.Class("grant-row"),
		h.Span(h.Class("who"), g.Text(row.Subject.Display)),
		h.Span(h.Class("kind"), g.Text(string(row.Subject.Kind))),
		h.Span(h.Class("verbs"), g.Text(row.Verbs)),
		h.Span(h.Class("at"), g.Text(row.GrantedAt)),
		g.If(csrf != "", h.FormEl(
			h.Class("revoke"),
			h.Method("post"),
			h.Action(UnsharePath),
			h.Input(h.Type("hidden"), h.Name(FieldCSRF), h.Value(csrf)),
			h.Input(h.Type("hidden"), h.Name(FieldGrant), h.Value(string(row.ID))),
			h.Button(h.Type("submit"), g.Text("Revoke")),
		)),
	)
}

// shareForm is the grant form.
//
// 🔴 THE RECIPIENT IS A `select` OVER `Candidates`, NOT A FREE-TEXT FIELD, AND THAT IS
// THE SAME DECISION `ControlSharing.Candidates` DOCUMENTS ONE LEVEL DOWN. A free-text
// id or email would make this form an existence oracle: type an address, learn from
// the refusal whether that person has an account here. A closed list cannot answer a
// question the caller could not already answer.
//
// ⚠ THE HANDLER RE-VALIDATES THE CHOICE AGAINST THE SAME LIST. A `select` constrains a
// browser, not an HTTP client, and this form's whole purpose is to be posted to.
func shareForm(v ShareView) g.Node {
	if len(v.Candidates) == 0 {
		return h.P(h.Class("empty"), g.Text(
			"There is nobody this credential can share with. Sharing is offered with the "+
				"people and projects you already share a project with; reaching anybody "+
				"else needs an invite, which this surface does not yet have."))
	}
	return h.FormEl(
		h.Class("share"),
		h.Method("post"),
		h.Action(SharePath),
		h.Input(h.Type("hidden"), h.Name(FieldCSRF), h.Value(v.CSRF)),
		h.Input(h.Type("hidden"), h.Name(FieldScope), h.Value(string(v.Scope.ID))),
		h.Label(h.For("subject"), g.Text("Share with")),
		h.Select(
			h.ID("subject"),
			h.Name(FieldSubject),
			h.Required(),
			g.Map(v.Candidates, func(s Subject) g.Node {
				return h.Option(h.Value(string(s.ID)), g.Text(s.Display+" ("+string(s.Kind)+")"))
			}),
		),
		h.FieldSet(
			h.Legend(g.Text("Permissions")),
			g.Map(grantableVerbs, func(vb control.Verb) g.Node {
				return h.Label(
					h.Input(
						h.Type("checkbox"),
						h.Name(FieldVerb),
						h.Value(string(vb)),
						// Read is pre-ticked because a grant with no verb is refused,
						// and a form whose default submission is an error teaches
						// people to ignore the error.
						g.If(vb == control.VerbRead, h.Checked()),
					),
					g.Text(string(vb)),
				)
			}),
		),
		h.Button(h.Type("submit"), g.Text("Share")),
	)
}

// grantableVerbs is what the form offers, in a fixed order.
//
// 🔴 IT IS `control.AllVerbs` RATHER THAN A LIST WRITTEN OUT HERE. A hand-written copy
// would silently stop offering a verb the model gained — a form that cannot express
// part of the authority model, with nothing going red. `admin` IS offered: it is what
// lets a recipient re-share, which is a real thing a person means to do, and leaving it
// out of the form would not take it out of the model.
var grantableVerbs = control.AllVerbs

// taskItem is the one href position that carries USER TEXT, and the only place
// [safeHref] is reached from.
//
// ⚠ IT IS NO LONGER THE ONLY HREF ON THE SURFACE. `scopeHref` and `entryHref` build
// same-origin browse links, and `scopeLink`'s comment says why neither goes through
// `safeHref`: that function ALLOWLISTS absolute http(s) and would refuse a relative path.
// The distinction that matters is the SOURCE of the URL, not its position — a task ref is
// a whole URL out of a store file, and these are constant paths with encoded operands.
//
// 🔴 A REF THAT DOES NOT PASS RENDERS AS TEXT RATHER THAN AS A DEAD LINK OR AS
// NOTHING. Dropping it would hide a fact the file carries; rendering `<a href="">`
// would put a clickable element on the page whose target the reader cannot see.
// Plain text is visible, inert, and says what the file says.
func taskItem(ref string) g.Node {
	href, ok := safeHref(ref)
	if !ok {
		return h.Li(h.Class("task refused"), g.Text(ref))
	}
	return h.Li(h.Class("task"), h.A(h.Href(href), g.Text(ref)))
}

// safeHref is the ONE place a URL reaches an href attribute, and it ALLOWLISTS.
//
// 🔴 A DENYLIST IS THE WRONG SHAPE HERE AND THAT IS NOT A STYLE PREFERENCE. The
// set of URL schemes a browser will execute is open — `javascript:`, `data:`,
// `vbscript:`, and whatever a handler registers — so a list of the ones to refuse
// is a list that is wrong the moment it is written. Two schemes are permitted, and
// a third requires an edit here.
//
// 🔴 THE SCHEME TEST IS CASE-INSENSITIVE AND WHITESPACE-STRIPPED BECAUSE BROWSERS
// ARE — AND WITH AN ALLOWLIST THAT PROTECTS THE *PERMIT* SIDE, WHICH IS THE OPPOSITE
// OF WHAT IT WOULD DO IN A DENYLIST. Measured, not reasoned: removing the
// `ToLower` makes `HTTPS://tracker.invalid/…` be REFUSED and changes nothing about
// `JaVaScRiPt:` — which an allowlist rejects at any casing, because it matches no
// permitted prefix however it is spelled. The same for the strip: removing it
// refuses `  https://…`. So neither is what stops the script-scheme attack; the
// allowlist is. What they buy is two real things: a correctly-spelled URL is not
// silently demoted to plain text, and the value written into the href is the
// STRIPPED one, so what the page shows and what the browser resolves are the same
// string. RFC 3986 §3.1 makes a scheme case-insensitive, and the HTML specification
// strips leading and trailing ASCII whitespace — including C0 controls — from a URL
// attribute before resolving it.
//
// ⚠ WHAT THIS DOES NOT CLAIM: it is not a URL validator. A permitted `https://`
// target may still be hostile — it may be a tracking pixel or a phishing page —
// and nothing here says otherwise. What it claims is narrower and is the property
// the escaper cannot supply: no value leaving this function can cause the BROWSER
// to execute the page author's string as code.
func safeHref(raw string) (string, bool) {
	// The HTML URL-attribute strip: ASCII whitespace and C0 controls at both ends.
	trimmed := strings.Trim(raw, "\x00\x01\x02\x03\x04\x05\x06\x07\x08\t\n\v\f\r\x0e\x0f"+
		"\x10\x11\x12\x13\x14\x15\x16\x17\x18\x19\x1a\x1b\x1c\x1d\x1e\x1f \x7f")
	if trimmed == "" {
		return "", false
	}
	lower := strings.ToLower(trimmed)
	for _, scheme := range allowedSchemes {
		if strings.HasPrefix(lower, scheme) {
			return trimmed, true
		}
	}
	return "", false
}

// allowedSchemes is the whole allowlist. Lowercase, with the separator included so
// that a host literally named `https` cannot pass as a scheme.
//
// 🔴 A RELATIVE URL IS NOT ON THIS LIST, DELIBERATELY. A ref beginning `/` would be
// a same-origin path, which sounds safe and is the shape that lets a store entry
// address any route this binary serves — including ones a later phase adds. The UI
// builds its own internal links from the ledger, never from user text.
var allowedSchemes = []string{"http://", "https://"}
