package redact

// Code generated by `go test ./internal/redact -run TestTheCleanDamageBudgetOverThisRepository
// -redact.write-budget`; see budget_test.go. Each key is 12 hex of SHA-256 over one damaged
// line's content; the comment names a file that holds it and the rule(s) that changed it.

// cleanBudget: the 19 lines of this repository's NEUTRAL files (not tests, test data or this
// package) that the redactor changes.
var cleanBudget = map[string]int{
	"865125456c44": 1, // .github/workflows/ci.yml (key-context)
	"b03150b17459": 1, // .github/workflows/ci.yml (key-context)
	"e5de326b8739": 1, // claudedocs/handoff-cairn-control-plane.md (key-context)
	"f5d678468a87": 1, // claudedocs/handoff-cairn-control-plane.md (url-userinfo-password)
	"446db735ea53": 1, // claudedocs/plan-cairn-agent-view.md (key-context)
	"4a398aaedb7c": 1, // claudedocs/plan-cairn-plugins.md (key-context)
	"8425edd8ecd4": 1, // claudedocs/plan-cairn-plugins.md (key-context)
	"d83e422d40fb": 1, // claudedocs/plan-cairn-plugins.md (url-userinfo-password)
	"323dcdabf67e": 1, // cmd/cairn-ui/main.go (key-context)
	"c21c633ba008": 1, // internal/depspolicy/depspolicy.go (key-context)
	"0dd4b5275717": 1, // internal/identity/config.go (key-context)
	"8b8c4b19a813": 1, // internal/pgstore/pgstore.go (url-userinfo-password)
	"656df869386b": 1, // internal/ui/README.md (entropy)
	"cb7617c4eb6e": 1, // internal/ui/returnto.go (key-context)
	"c20f31cc44f3": 1, // server/README.md (key-context)
	"d562367c8723": 1, // server/seed.sh (curl-user)
	"5068ddc515e1": 1, // server/server.py (key-context)
	"9086c567d2c5": 1, // uiaudit/presence.go (key-context)
	"7923611f4a1a": 1, // uiaudit/vendor-js/axe.min.js (key-context)
}

// fixtureDamageCeiling: the damaged lines of the FIXTURE files, measured, plus a tenth.
const fixtureDamageCeiling = 254 // measured: 231
